# %% IMPORTS
from BaseClasses import ItemClassification

from .core import CivVUsefulItemData
from ..enums import CivVItemType

# All declaration
__all__ = [
    "POLICY_ITEMS",
]


# %% ITEM DECLARATIONS
POLICY_ITEMS = {
    "Liberty": CivVUsefulItemData(
        name="Liberty",
        type=CivVItemType.policy,
        game_ids=[0],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Collective Rule": CivVUsefulItemData(
        name="Collective Rule",
        type=CivVItemType.policy,
        game_ids=[1],
        classification=ItemClassification.useful,
    ),
    "Citizenship": CivVUsefulItemData(
        name="Citizenship",
        type=CivVItemType.policy,
        game_ids=[2],
        classification=ItemClassification.useful,
    ),
    "Republic": CivVUsefulItemData(
        name="Republic",
        type=CivVItemType.policy,
        game_ids=[3],
        classification=ItemClassification.useful,
    ),
    "Representation": CivVUsefulItemData(
        name="Representation",
        type=CivVItemType.policy,
        game_ids=[4],
        classification=ItemClassification.useful,
    ),
    "Meritocracy": CivVUsefulItemData(
        name="Meritocracy",
        type=CivVItemType.policy,
        game_ids=[5],
        classification=ItemClassification.useful,
    ),
    "Tradition": CivVUsefulItemData(
        name="Tradition",
        type=CivVItemType.policy,
        game_ids=[6],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Aristocracy": CivVUsefulItemData(
        name="Aristocracy",
        type=CivVItemType.policy,
        game_ids=[7],
        classification=ItemClassification.useful,
    ),
    "Oligarchy": CivVUsefulItemData(
        name="Oligarchy",
        type=CivVItemType.policy,
        game_ids=[8],
        classification=ItemClassification.useful,
    ),
    "Legalism": CivVUsefulItemData(
        name="Legalism",
        type=CivVItemType.policy,
        game_ids=[9],
        classification=ItemClassification.useful,
    ),
    "Landed Elite": CivVUsefulItemData(
        name="Landed Elite",
        type=CivVItemType.policy,
        game_ids=[10],
        classification=ItemClassification.useful,
    ),
    "Monarchy": CivVUsefulItemData(
        name="Monarchy",
        type=CivVItemType.policy,
        game_ids=[11],
        classification=ItemClassification.useful,
    ),
    "Honor": CivVUsefulItemData(
        name="Honor",
        type=CivVItemType.policy,
        game_ids=[12],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Warrior Code": CivVUsefulItemData(
        name="Warrior Code",
        type=CivVItemType.policy,
        game_ids=[13],
        classification=ItemClassification.useful,
    ),
    "Discipline": CivVUsefulItemData(
        name="Discipline",
        type=CivVItemType.policy,
        game_ids=[14],
        classification=ItemClassification.useful,
    ),
    "Military Tradition": CivVUsefulItemData(
        name="Military Tradition",
        type=CivVItemType.policy,
        game_ids=[15],
        classification=ItemClassification.useful,
    ),
    "Military Caste": CivVUsefulItemData(
        name="Military Caste",
        type=CivVItemType.policy,
        game_ids=[16],
        classification=ItemClassification.useful,
    ),
    "Professional Army": CivVUsefulItemData(
        name="Professional Army",
        type=CivVItemType.policy,
        game_ids=[17],
        classification=ItemClassification.useful,
    ),
    "Piety": CivVUsefulItemData(
        name="Piety",
        type=CivVItemType.policy,
        game_ids=[18],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Organized Religion": CivVUsefulItemData(
        name="Organized Religion",
        type=CivVItemType.policy,
        game_ids=[19],
        classification=ItemClassification.useful,
    ),
    "Mandate of Heaven": CivVUsefulItemData(
        name="Mandate of Heaven",
        type=CivVItemType.policy,
        game_ids=[20],
        classification=ItemClassification.useful,
    ),
    "Theocracy": CivVUsefulItemData(
        name="Theocracy",
        type=CivVItemType.policy,
        game_ids=[21],
        classification=ItemClassification.useful,
    ),
    "Reformation": CivVUsefulItemData(
        name="Reformation",
        type=CivVItemType.policy,
        game_ids=[22],
        classification=ItemClassification.useful,
    ),
    "Religious Tolerance": CivVUsefulItemData(
        name="Religious Tolerance",
        type=CivVItemType.policy,
        game_ids=[23],
        classification=ItemClassification.useful,
    ),
    "Patronage": CivVUsefulItemData(
        name="Patronage",
        type=CivVItemType.policy,
        game_ids=[24],
        classification=ItemClassification.progression,
        prefix="Policy Branch",
    ),
    "Philanthropy": CivVUsefulItemData(
        name="Philanthropy",
        type=CivVItemType.policy,
        game_ids=[25],
        classification=ItemClassification.progression,
    ),
    "Consulates": CivVUsefulItemData(
        name="Consulates",
        type=CivVItemType.policy,
        game_ids=[26],
        classification=ItemClassification.progression,
    ),
    "Scholasticism": CivVUsefulItemData(
        name="Scholasticism",
        type=CivVItemType.policy,
        game_ids=[27],
        classification=ItemClassification.useful,
    ),
    "Cultural Diplomacy": CivVUsefulItemData(
        name="Cultural Diplomacy",
        type=CivVItemType.policy,
        game_ids=[28],
        classification=ItemClassification.useful,
    ),
    "Merchant Confederacy": CivVUsefulItemData(
        name="Merchant Confederacy",
        type=CivVItemType.policy,
        game_ids=[29],
        classification=ItemClassification.useful,
    ),
    "Commerce": CivVUsefulItemData(
        name="Commerce",
        type=CivVItemType.policy,
        game_ids=[30],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Trade Unions": CivVUsefulItemData(
        name="Trade Unions",
        type=CivVItemType.policy,
        game_ids=[31],
        classification=ItemClassification.useful,
    ),
    "Entrepreneurship": CivVUsefulItemData(
        name="Entrepreneurship",
        type=CivVItemType.policy,
        game_ids=[32],
        classification=ItemClassification.useful,
    ),
    "Mercantilism": CivVUsefulItemData(
        name="Mercantilism",
        type=CivVItemType.policy,
        game_ids=[33],
        classification=ItemClassification.useful,
    ),
    "Caravans": CivVUsefulItemData(
        name="Caravans",
        type=CivVItemType.policy,
        game_ids=[34],
        classification=ItemClassification.useful,
    ),
    "Protectionism": CivVUsefulItemData(
        name="Protectionism",
        type=CivVItemType.policy,
        game_ids=[35],
        classification=ItemClassification.useful,
    ),
    "Rationalism": CivVUsefulItemData(
        name="Rationalism",
        type=CivVItemType.policy,
        game_ids=[36],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Secularism": CivVUsefulItemData(
        name="Secularism",
        type=CivVItemType.policy,
        game_ids=[37],
        classification=ItemClassification.useful,
    ),
    "Humanism": CivVUsefulItemData(
        name="Humanism",
        type=CivVItemType.policy,
        game_ids=[38],
        classification=ItemClassification.useful,
    ),
    "Free Thought": CivVUsefulItemData(
        name="Free Thought",
        type=CivVItemType.policy,
        game_ids=[39],
        classification=ItemClassification.useful,
    ),
    "Sovereignty": CivVUsefulItemData(
        name="Sovereignty",
        type=CivVItemType.policy,
        game_ids=[40],
        classification=ItemClassification.useful,
    ),
    "Scientific Revolution": CivVUsefulItemData(
        name="Scientific Revolution",
        type=CivVItemType.policy,
        game_ids=[41],
        classification=ItemClassification.useful,
    ),
    "Tradition Finisher": CivVUsefulItemData(
        name="Tradition Finisher",
        type=CivVItemType.policy,
        game_ids=[42],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Liberty Finisher": CivVUsefulItemData(
        name="Liberty Finisher",
        type=CivVItemType.policy,
        game_ids=[43],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Honor Finisher": CivVUsefulItemData(
        name="Honor Finisher",
        type=CivVItemType.policy,
        game_ids=[44],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Piety Finisher": CivVUsefulItemData(
        name="Piety Finisher",
        type=CivVItemType.policy,
        game_ids=[45],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Patronage Finisher": CivVUsefulItemData(
        name="Patronage Finisher",
        type=CivVItemType.policy,
        game_ids=[46],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Commerce Finisher": CivVUsefulItemData(
        name="Commerce Finisher",
        type=CivVItemType.policy,
        game_ids=[47],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Rationalism Finisher": CivVUsefulItemData(
        name="Rationalism Finisher",
        type=CivVItemType.policy,
        game_ids=[48],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Aesthetics": CivVUsefulItemData(
        name="Aesthetics",
        type=CivVItemType.policy,
        game_ids=[49],
        classification=ItemClassification.progression,
        prefix="Policy Branch",
    ),
    "Cultural Centers": CivVUsefulItemData(
        name="Cultural Centers",
        type=CivVItemType.policy,
        game_ids=[50],
        classification=ItemClassification.useful,
    ),
    "Fine Arts": CivVUsefulItemData(
        name="Fine Arts",
        type=CivVItemType.policy,
        game_ids=[51],
        classification=ItemClassification.useful,
    ),
    "Flourishing of the Arts": CivVUsefulItemData(
        name="Flourishing of the Arts",
        type=CivVItemType.policy,
        game_ids=[52],
        classification=ItemClassification.useful,
    ),
    "Artistic Genius": CivVUsefulItemData(
        name="Artistic Genius",
        type=CivVItemType.policy,
        game_ids=[53],
        classification=ItemClassification.useful,
    ),
    "Cultural Exchange": CivVUsefulItemData(
        name="Cultural Exchange",
        type=CivVItemType.policy,
        game_ids=[54],
        classification=ItemClassification.progression,
    ),
    "Aesthetics Finisher": CivVUsefulItemData(
        name="Aesthetics Finisher",
        type=CivVItemType.policy,
        game_ids=[55],
        classification=ItemClassification.progression,
        prefix="Policy Branch",
    ),
    "Exploration": CivVUsefulItemData(
        name="Exploration",
        type=CivVItemType.policy,
        game_ids=[56],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
    "Maritime Infrastructure": CivVUsefulItemData(
        name="Maritime Infrastructure",
        type=CivVItemType.policy,
        game_ids=[57],
        classification=ItemClassification.useful,
    ),
    "Naval Tradition": CivVUsefulItemData(
        name="Naval Tradition",
        type=CivVItemType.policy,
        game_ids=[58],
        classification=ItemClassification.useful,
    ),
    "Merchant Navy": CivVUsefulItemData(
        name="Merchant Navy",
        type=CivVItemType.policy,
        game_ids=[59],
        classification=ItemClassification.useful,
    ),
    "Navigation School": CivVUsefulItemData(
        name="Navigation School",
        type=CivVItemType.policy,
        game_ids=[60],
        classification=ItemClassification.useful,
    ),
    "Treasure Fleets": CivVUsefulItemData(
        name="Treasure Fleets",
        type=CivVItemType.policy,
        game_ids=[61],
        classification=ItemClassification.useful,
    ),
    "Exploration Finisher": CivVUsefulItemData(
        name="Exploration Finisher",
        type=CivVItemType.policy,
        game_ids=[62],
        classification=ItemClassification.useful,
        prefix="Policy Branch",
    ),
}
"Dict of all policies"
