# %% IMPORTS
from .core import CivVProgressionItemData, CivVProgressiveItemData
from ..enums import CivVItemGroup, CivVItemType

# All declaration
__all__ = [
    "PROGRESSIVE_TECH_ITEMS",
    "TECH_ITEMS",
]


# %% ITEM DECLARATIONS
PROGRESSIVE_TECH_ITEMS: dict[str, CivVProgressiveItemData] = {
    "Growth": CivVProgressiveItemData(
        name="Progressive Growth",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Production": CivVProgressiveItemData(
        name="Progressive Production",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Science": CivVProgressiveItemData(
        name="Progressive Science",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Culture": CivVProgressiveItemData(
        name="Progressive Culture",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Gold": CivVProgressiveItemData(
        name="Progressive Gold",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Happiness": CivVProgressiveItemData(
        name="Progressive Happiness",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Navy": CivVProgressiveItemData(
        name="Progressive Navy",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Melee Unit": CivVProgressiveItemData(
        name="Progressive Melee Unit",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Ranged Unit": CivVProgressiveItemData(
        name="Progressive Ranged Unit",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Siege Unit": CivVProgressiveItemData(
        name="Progressive Siege Unit",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
    "Misc": CivVProgressiveItemData(
        name="Progressive Misc",
        type=CivVItemType.tech,
        option_toggle_name="progressive_techs",
    ),
}
"Dict of all progressive technologies"


TECH_ITEMS: dict[str, CivVProgressionItemData] = {
    "Pottery": CivVProgressionItemData(
        name="Pottery",
        type=CivVItemType.tech,
        game_id=1,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Growth"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Animal Husbandry": CivVProgressionItemData(
        name="Animal Husbandry",
        type=CivVItemType.tech,
        game_id=2,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Gold"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Archery": CivVProgressionItemData(
        name="Archery",
        type=CivVItemType.tech,
        game_id=3,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Ranged Unit"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Mining": CivVProgressionItemData(
        name="Mining",
        type=CivVItemType.tech,
        game_id=4,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Production"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Sailing": CivVProgressionItemData(
        name="Sailing",
        type=CivVItemType.tech,
        game_id=5,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Calendar": CivVProgressionItemData(
        name="Calendar",
        type=CivVItemType.tech,
        game_id=6,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Happiness"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Writing": CivVProgressionItemData(
        name="Writing",
        type=CivVItemType.tech,
        game_id=7,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Trapping": CivVProgressionItemData(
        name="Trapping",
        type=CivVItemType.tech,
        game_id=8,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Happiness"],
        groups={CivVItemGroup.ancient_era},
    ),
    "The Wheel": CivVProgressionItemData(
        name="The Wheel",
        type=CivVItemType.tech,
        game_id=9,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Misc"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Masonry": CivVProgressionItemData(
        name="Masonry",
        type=CivVItemType.tech,
        game_id=10,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Production"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Bronze Working": CivVProgressionItemData(
        name="Bronze Working",
        type=CivVItemType.tech,
        game_id=11,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.ancient_era},
    ),
    "Optics": CivVProgressionItemData(
        name="Optics",
        type=CivVItemType.tech,
        game_id=12,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.classical_era},
    ),
    "Horseback Riding": CivVProgressionItemData(
        name="Horseback Riding",
        type=CivVItemType.tech,
        game_id=13,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.classical_era},
    ),
    "Mathematics": CivVProgressionItemData(
        name="Mathematics",
        type=CivVItemType.tech,
        game_id=14,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Siege Unit"],
        groups={CivVItemGroup.classical_era},
    ),
    "Construction": CivVProgressionItemData(
        name="Construction",
        type=CivVItemType.tech,
        game_id=15,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Happiness"],
        groups={CivVItemGroup.classical_era},
    ),
    "Philosophy": CivVProgressionItemData(
        name="Philosophy",
        type=CivVItemType.tech,
        game_id=16,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Misc"],
        groups={CivVItemGroup.classical_era},
    ),
    "Drama and Poetry": CivVProgressionItemData(
        name="Drama and Poetry",
        type=CivVItemType.tech,
        game_id=17,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Culture"],
        groups={CivVItemGroup.classical_era},
    ),
    "Currency": CivVProgressionItemData(
        name="Currency",
        type=CivVItemType.tech,
        game_id=18,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Gold"],
        groups={CivVItemGroup.classical_era},
    ),
    "Engineering": CivVProgressionItemData(
        name="Engineering",
        type=CivVItemType.tech,
        game_id=19,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Growth"],
        groups={CivVItemGroup.classical_era},
    ),
    "Iron Working": CivVProgressionItemData(
        name="Iron Working",
        type=CivVItemType.tech,
        game_id=20,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.classical_era},
    ),
    "Theology": CivVProgressionItemData(
        name="Theology",
        type=CivVItemType.tech,
        game_id=21,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Misc"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Civil Service": CivVProgressionItemData(
        name="Civil Service",
        type=CivVItemType.tech,
        game_id=22,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Growth"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Guilds": CivVProgressionItemData(
        name="Guilds",
        type=CivVItemType.tech,
        game_id=23,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Gold"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Metal Casting": CivVProgressionItemData(
        name="Metal Casting",
        type=CivVItemType.tech,
        game_id=24,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Production"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Compass": CivVProgressionItemData(
        name="Compass",
        type=CivVItemType.tech,
        game_id=25,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Education": CivVProgressionItemData(
        name="Education",
        type=CivVItemType.tech,
        game_id=26,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Chivalry": CivVProgressionItemData(
        name="Chivalry",
        type=CivVItemType.tech,
        game_id=27,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Machinery": CivVProgressionItemData(
        name="Machinery",
        type=CivVItemType.tech,
        game_id=28,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Ranged Unit"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Physics": CivVProgressionItemData(
        name="Physics",
        type=CivVItemType.tech,
        game_id=29,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Siege Unit"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Steel": CivVProgressionItemData(
        name="Steel",
        type=CivVItemType.tech,
        game_id=30,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.medieval_era},
    ),
    "Astronomy": CivVProgressionItemData(
        name="Astronomy",
        type=CivVItemType.tech,
        game_id=31,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Acoustics": CivVProgressionItemData(
        name="Acoustics",
        type=CivVItemType.tech,
        game_id=32,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Culture"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Banking": CivVProgressionItemData(
        name="Banking",
        type=CivVItemType.tech,
        game_id=33,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Gold"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Printing Press": CivVProgressionItemData(
        name="Printing Press",
        type=CivVItemType.tech,
        game_id=34,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Happiness"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Gunpowder": CivVProgressionItemData(
        name="Gunpowder",
        type=CivVItemType.tech,
        game_id=35,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Navigation": CivVProgressionItemData(
        name="Navigation",
        type=CivVItemType.tech,
        game_id=36,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Architecture": CivVProgressionItemData(
        name="Architecture",
        type=CivVItemType.tech,
        game_id=37,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Misc"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Economics": CivVProgressionItemData(
        name="Economics",
        type=CivVItemType.tech,
        game_id=38,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Gold"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Metallurgy": CivVProgressionItemData(
        name="Metallurgy",
        type=CivVItemType.tech,
        game_id=39,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Chemistry": CivVProgressionItemData(
        name="Chemistry",
        type=CivVItemType.tech,
        game_id=40,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Siege Unit"],
        groups={CivVItemGroup.renaissance_era},
    ),
    "Archaeology": CivVProgressionItemData(
        name="Archaeology",
        type=CivVItemType.tech,
        game_id=41,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Culture"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Scientific Theory": CivVProgressionItemData(
        name="Scientific Theory",
        type=CivVItemType.tech,
        game_id=42,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Industrialization": CivVProgressionItemData(
        name="Industrialization",
        type=CivVItemType.tech,
        game_id=43,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Production"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Rifling": CivVProgressionItemData(
        name="Rifling",
        type=CivVItemType.tech,
        game_id=44,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Military Science": CivVProgressionItemData(
        name="Military Science",
        type=CivVItemType.tech,
        game_id=45,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Fertilizer": CivVProgressionItemData(
        name="Fertilizer",
        type=CivVItemType.tech,
        game_id=46,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Growth"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Biology": CivVProgressionItemData(
        name="Biology",
        type=CivVItemType.tech,
        game_id=47,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Growth"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Electricity": CivVProgressionItemData(
        name="Electricity",
        type=CivVItemType.tech,
        game_id=48,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Gold"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Steam Power": CivVProgressionItemData(
        name="Steam Power",
        type=CivVItemType.tech,
        game_id=49,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Dynamite": CivVProgressionItemData(
        name="Dynamite",
        type=CivVItemType.tech,
        game_id=50,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Siege Unit"],
        groups={CivVItemGroup.industrial_era},
    ),
    "Refrigeration": CivVProgressionItemData(
        name="Refrigeration",
        type=CivVItemType.tech,
        game_id=51,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Happiness"],
        groups={CivVItemGroup.modern_era},
    ),
    "Radio": CivVProgressionItemData(
        name="Radio",
        type=CivVItemType.tech,
        game_id=52,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Culture"],
        groups={CivVItemGroup.modern_era},
    ),
    "Replaceable Parts": CivVProgressionItemData(
        name="Replaceable Parts",
        type=CivVItemType.tech,
        game_id=53,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.modern_era},
    ),
    "Flight": CivVProgressionItemData(
        name="Flight",
        type=CivVItemType.tech,
        game_id=54,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Ranged Unit"],
        groups={CivVItemGroup.modern_era},
    ),
    "Railroad": CivVProgressionItemData(
        name="Railroad",
        type=CivVItemType.tech,
        game_id=55,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Misc"],
        groups={CivVItemGroup.modern_era},
    ),
    "Plastics": CivVProgressionItemData(
        name="Plastics",
        type=CivVItemType.tech,
        game_id=56,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.modern_era},
    ),
    "Electronics": CivVProgressionItemData(
        name="Electronics",
        type=CivVItemType.tech,
        game_id=57,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Ranged Unit"],
        groups={CivVItemGroup.modern_era},
    ),
    "Ballistics": CivVProgressionItemData(
        name="Ballistics",
        type=CivVItemType.tech,
        game_id=58,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Ranged Unit"],
        groups={CivVItemGroup.modern_era},
    ),
    "Combustion": CivVProgressionItemData(
        name="Combustion",
        type=CivVItemType.tech,
        game_id=59,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.modern_era},
    ),
    "Penicillin": CivVProgressionItemData(
        name="Penicillin",
        type=CivVItemType.tech,
        game_id=60,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Growth"],
        groups={CivVItemGroup.atomic_era},
    ),
    "Atomic Theory": CivVProgressionItemData(
        name="Atomic Theory",
        type=CivVItemType.tech,
        game_id=61,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Siege Unit"],
        groups={CivVItemGroup.atomic_era},
    ),
    "Radar": CivVProgressionItemData(
        name="Radar",
        type=CivVItemType.tech,
        game_id=62,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Ranged Unit"],
        groups={CivVItemGroup.atomic_era},
    ),
    "Combined Arms": CivVProgressionItemData(
        name="Combined Arms",
        type=CivVItemType.tech,
        game_id=63,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.atomic_era},
    ),
    "Ecology": CivVProgressionItemData(
        name="Ecology",
        type=CivVItemType.tech,
        game_id=64,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Production"],
        groups={CivVItemGroup.atomic_era},
    ),
    "Nuclear Fission": CivVProgressionItemData(
        name="Nuclear Fission",
        type=CivVItemType.tech,
        game_id=65,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Siege Unit"],
        groups={CivVItemGroup.atomic_era},
    ),
    "Rocketry": CivVProgressionItemData(
        name="Rocketry",
        type=CivVItemType.tech,
        game_id=66,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.atomic_era},
    ),
    "Computers": CivVProgressionItemData(
        name="Computers",
        type=CivVItemType.tech,
        game_id=67,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.atomic_era},
    ),
    "Telecommunications": CivVProgressionItemData(
        name="Telecommunications",
        type=CivVItemType.tech,
        game_id=68,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.information_era},
    ),
    "Mobile Tactics": CivVProgressionItemData(
        name="Mobile Tactics",
        type=CivVItemType.tech,
        game_id=69,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.information_era},
    ),
    "Advanced Ballistics": CivVProgressionItemData(
        name="Advanced Ballistics",
        type=CivVItemType.tech,
        game_id=70,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.information_era},
    ),
    "Satellites": CivVProgressionItemData(
        name="Satellites",
        type=CivVItemType.tech,
        game_id=71,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.information_era},
    ),
    "Robotics": CivVProgressionItemData(
        name="Robotics",
        type=CivVItemType.tech,
        game_id=72,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Navy"],
        groups={CivVItemGroup.information_era},
    ),
    "Lasers": CivVProgressionItemData(
        name="Lasers",
        type=CivVItemType.tech,
        game_id=73,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.information_era},
    ),
    "The Internet": CivVProgressionItemData(
        name="The Internet",
        type=CivVItemType.tech,
        game_id=74,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Culture"],
        groups={CivVItemGroup.information_era},
    ),
    "Globalization": CivVProgressionItemData(
        name="Globalization",
        type=CivVItemType.tech,
        game_id=75,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Gold"],
        groups={CivVItemGroup.information_era},
    ),
    "Particle Physics": CivVProgressionItemData(
        name="Particle Physics",
        type=CivVItemType.tech,
        game_id=76,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.information_era},
    ),
    "Nuclear Fusion": CivVProgressionItemData(
        name="Nuclear Fusion",
        type=CivVItemType.tech,
        game_id=77,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Melee Unit"],
        groups={CivVItemGroup.information_era},
    ),
    "Nanotechnology": CivVProgressionItemData(
        name="Nanotechnology",
        type=CivVItemType.tech,
        game_id=78,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Science"],
        groups={CivVItemGroup.information_era},
    ),
    "Stealth": CivVProgressionItemData(
        name="Stealth",
        type=CivVItemType.tech,
        game_id=79,
        progressive_parent=PROGRESSIVE_TECH_ITEMS["Ranged Unit"],
        groups={CivVItemGroup.information_era},
    ),
}
"Dict of all technologies"
