# %% IMPORTS
from BaseClasses import ItemClassification

from .core import CivVUsefulItemData
from ..enums import CivVItemGroup, CivVItemType

# All declaration
__all__ = [
    "PROGRESSIVE_TECH_ITEMS",
    "TECH_ITEMS",
]


# %% ITEM DECLARATIONS
TECH_ITEMS = {
    "Pottery": CivVUsefulItemData(
        name="Pottery",
        type=CivVItemType.tech,
        game_ids=[1],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Animal Husbandry": CivVUsefulItemData(
        name="Animal Husbandry",
        type=CivVItemType.tech,
        game_ids=[2],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Archery": CivVUsefulItemData(
        name="Archery",
        type=CivVItemType.tech,
        game_ids=[3],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Mining": CivVUsefulItemData(
        name="Mining",
        type=CivVItemType.tech,
        game_ids=[4],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Sailing": CivVUsefulItemData(
        name="Sailing",
        type=CivVItemType.tech,
        game_ids=[5],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Calendar": CivVUsefulItemData(
        name="Calendar",
        type=CivVItemType.tech,
        game_ids=[6],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Writing": CivVUsefulItemData(
        name="Writing",
        type=CivVItemType.tech,
        game_ids=[7],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Trapping": CivVUsefulItemData(
        name="Trapping",
        type=CivVItemType.tech,
        game_ids=[8],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "The Wheel": CivVUsefulItemData(
        name="The Wheel",
        type=CivVItemType.tech,
        game_ids=[9],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Masonry": CivVUsefulItemData(
        name="Masonry",
        type=CivVItemType.tech,
        game_ids=[10],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Bronze Working": CivVUsefulItemData(
        name="Bronze Working",
        type=CivVItemType.tech,
        game_ids=[11],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.ancient_era},
    ),
    "Optics": CivVUsefulItemData(
        name="Optics",
        type=CivVItemType.tech,
        game_ids=[12],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Horseback Riding": CivVUsefulItemData(
        name="Horseback Riding",
        type=CivVItemType.tech,
        game_ids=[13],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Mathematics": CivVUsefulItemData(
        name="Mathematics",
        type=CivVItemType.tech,
        game_ids=[14],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Construction": CivVUsefulItemData(
        name="Construction",
        type=CivVItemType.tech,
        game_ids=[15],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Philosophy": CivVUsefulItemData(
        name="Philosophy",
        type=CivVItemType.tech,
        game_ids=[16],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Drama and Poetry": CivVUsefulItemData(
        name="Drama and Poetry",
        type=CivVItemType.tech,
        game_ids=[17],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Currency": CivVUsefulItemData(
        name="Currency",
        type=CivVItemType.tech,
        game_ids=[18],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Engineering": CivVUsefulItemData(
        name="Engineering",
        type=CivVItemType.tech,
        game_ids=[19],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Iron Working": CivVUsefulItemData(
        name="Iron Working",
        type=CivVItemType.tech,
        game_ids=[20],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.classical_era},
    ),
    "Theology": CivVUsefulItemData(
        name="Theology",
        type=CivVItemType.tech,
        game_ids=[21],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Civil Service": CivVUsefulItemData(
        name="Civil Service",
        type=CivVItemType.tech,
        game_ids=[22],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Guilds": CivVUsefulItemData(
        name="Guilds",
        type=CivVItemType.tech,
        game_ids=[23],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Metal Casting": CivVUsefulItemData(
        name="Metal Casting",
        type=CivVItemType.tech,
        game_ids=[24],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Compass": CivVUsefulItemData(
        name="Compass",
        type=CivVItemType.tech,
        game_ids=[25],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Education": CivVUsefulItemData(
        name="Education",
        type=CivVItemType.tech,
        game_ids=[26],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Chivalry": CivVUsefulItemData(
        name="Chivalry",
        type=CivVItemType.tech,
        game_ids=[27],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Machinery": CivVUsefulItemData(
        name="Machinery",
        type=CivVItemType.tech,
        game_ids=[28],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Physics": CivVUsefulItemData(
        name="Physics",
        type=CivVItemType.tech,
        game_ids=[29],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Steel": CivVUsefulItemData(
        name="Steel",
        type=CivVItemType.tech,
        game_ids=[30],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.medieval_era},
    ),
    "Astronomy": CivVUsefulItemData(
        name="Astronomy",
        type=CivVItemType.tech,
        game_ids=[31],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Acoustics": CivVUsefulItemData(
        name="Acoustics",
        type=CivVItemType.tech,
        game_ids=[32],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Banking": CivVUsefulItemData(
        name="Banking",
        type=CivVItemType.tech,
        game_ids=[33],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Printing Press": CivVUsefulItemData(
        name="Printing Press",
        type=CivVItemType.tech,
        game_ids=[34],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Gunpowder": CivVUsefulItemData(
        name="Gunpowder",
        type=CivVItemType.tech,
        game_ids=[35],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Navigation": CivVUsefulItemData(
        name="Navigation",
        type=CivVItemType.tech,
        game_ids=[36],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Architecture": CivVUsefulItemData(
        name="Architecture",
        type=CivVItemType.tech,
        game_ids=[37],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Economics": CivVUsefulItemData(
        name="Economics",
        type=CivVItemType.tech,
        game_ids=[38],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Metallurgy": CivVUsefulItemData(
        name="Metallurgy",
        type=CivVItemType.tech,
        game_ids=[39],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Chemistry": CivVUsefulItemData(
        name="Chemistry",
        type=CivVItemType.tech,
        game_ids=[40],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.renaissance_era},
    ),
    "Archaeology": CivVUsefulItemData(
        name="Archaeology",
        type=CivVItemType.tech,
        game_ids=[41],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Scientific Theory": CivVUsefulItemData(
        name="Scientific Theory",
        type=CivVItemType.tech,
        game_ids=[42],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Industrialization": CivVUsefulItemData(
        name="Industrialization",
        type=CivVItemType.tech,
        game_ids=[43],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Rifling": CivVUsefulItemData(
        name="Rifling",
        type=CivVItemType.tech,
        game_ids=[44],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Military Science": CivVUsefulItemData(
        name="Military Science",
        type=CivVItemType.tech,
        game_ids=[45],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Fertilizer": CivVUsefulItemData(
        name="Fertilizer",
        type=CivVItemType.tech,
        game_ids=[46],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Biology": CivVUsefulItemData(
        name="Biology",
        type=CivVItemType.tech,
        game_ids=[47],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Electricity": CivVUsefulItemData(
        name="Electricity",
        type=CivVItemType.tech,
        game_ids=[48],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Steam Power": CivVUsefulItemData(
        name="Steam Power",
        type=CivVItemType.tech,
        game_ids=[49],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Dynamite": CivVUsefulItemData(
        name="Dynamite",
        type=CivVItemType.tech,
        game_ids=[50],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.industrial_era},
    ),
    "Refrigeration": CivVUsefulItemData(
        name="Refrigeration",
        type=CivVItemType.tech,
        game_ids=[51],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Radio": CivVUsefulItemData(
        name="Radio",
        type=CivVItemType.tech,
        game_ids=[52],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Replaceable Parts": CivVUsefulItemData(
        name="Replaceable Parts",
        type=CivVItemType.tech,
        game_ids=[53],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Flight": CivVUsefulItemData(
        name="Flight",
        type=CivVItemType.tech,
        game_ids=[54],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Railroad": CivVUsefulItemData(
        name="Railroad",
        type=CivVItemType.tech,
        game_ids=[55],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Plastics": CivVUsefulItemData(
        name="Plastics",
        type=CivVItemType.tech,
        game_ids=[56],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Electronics": CivVUsefulItemData(
        name="Electronics",
        type=CivVItemType.tech,
        game_ids=[57],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Ballistics": CivVUsefulItemData(
        name="Ballistics",
        type=CivVItemType.tech,
        game_ids=[58],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Combustion": CivVUsefulItemData(
        name="Combustion",
        type=CivVItemType.tech,
        game_ids=[59],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.modern_era},
    ),
    "Penicillin": CivVUsefulItemData(
        name="Penicillin",
        type=CivVItemType.tech,
        game_ids=[60],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.atomic_era},
    ),
    "Atomic Theory": CivVUsefulItemData(
        name="Atomic Theory",
        type=CivVItemType.tech,
        game_ids=[61],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.atomic_era},
    ),
    "Radar": CivVUsefulItemData(
        name="Radar",
        type=CivVItemType.tech,
        game_ids=[62],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.atomic_era},
    ),
    "Combined Arms": CivVUsefulItemData(
        name="Combined Arms",
        type=CivVItemType.tech,
        game_ids=[63],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.atomic_era},
    ),
    "Ecology": CivVUsefulItemData(
        name="Ecology",
        type=CivVItemType.tech,
        game_ids=[64],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.atomic_era},
    ),
    "Nuclear Fission": CivVUsefulItemData(
        name="Nuclear Fission",
        type=CivVItemType.tech,
        game_ids=[65],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.atomic_era},
    ),
    "Rocketry": CivVUsefulItemData(
        name="Rocketry",
        type=CivVItemType.tech,
        game_ids=[66],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.atomic_era},
    ),
    "Computers": CivVUsefulItemData(
        name="Computers",
        type=CivVItemType.tech,
        game_ids=[67],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.atomic_era},
    ),
    "Telecommunications": CivVUsefulItemData(
        name="Telecommunications",
        type=CivVItemType.tech,
        game_ids=[68],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Mobile Tactics": CivVUsefulItemData(
        name="Mobile Tactics",
        type=CivVItemType.tech,
        game_ids=[69],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Advanced Ballistics": CivVUsefulItemData(
        name="Advanced Ballistics",
        type=CivVItemType.tech,
        game_ids=[70],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Satellites": CivVUsefulItemData(
        name="Satellites",
        type=CivVItemType.tech,
        game_ids=[71],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Robotics": CivVUsefulItemData(
        name="Robotics",
        type=CivVItemType.tech,
        game_ids=[72],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Lasers": CivVUsefulItemData(
        name="Lasers",
        type=CivVItemType.tech,
        game_ids=[73],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "The Internet": CivVUsefulItemData(
        name="The Internet",
        type=CivVItemType.tech,
        game_ids=[74],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Globalization": CivVUsefulItemData(
        name="Globalization",
        type=CivVItemType.tech,
        game_ids=[75],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Particle Physics": CivVUsefulItemData(
        name="Particle Physics",
        type=CivVItemType.tech,
        game_ids=[76],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Nuclear Fusion": CivVUsefulItemData(
        name="Nuclear Fusion",
        type=CivVItemType.tech,
        game_ids=[77],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Nanotechnology": CivVUsefulItemData(
        name="Nanotechnology",
        type=CivVItemType.tech,
        game_ids=[78],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
    "Stealth": CivVUsefulItemData(
        name="Stealth",
        type=CivVItemType.tech,
        game_ids=[79],
        classification=ItemClassification.progression,
        groups={CivVItemGroup.information_era},
    ),
}
"Dict of all technologies"


PROGRESSIVE_TECH_ITEMS = {
    "Progressive Growth": CivVUsefulItemData(
        name="Progressive Growth",
        type=CivVItemType.tech,
        game_ids=[1, 19, 22, 46, 47, 60],
        classification=ItemClassification.progression,
    ),
    "Progressive Production": CivVUsefulItemData(
        name="Progressive Production",
        type=CivVItemType.tech,
        game_ids=[4, 10, 24, 43, 64],
        classification=ItemClassification.progression,
    ),
    "Progressive Science": CivVUsefulItemData(
        name="Progressive Science",
        type=CivVItemType.tech,
        game_ids=[7, 26, 42, 56, 66, 70, 71, 76, 78],
        classification=ItemClassification.progression,
    ),
    "Progressive Culture": CivVUsefulItemData(
        name="Progressive Culture",
        type=CivVItemType.tech,
        game_ids=[17, 32, 41, 52, 74],
        classification=ItemClassification.progression,
    ),
    "Progressive Gold": CivVUsefulItemData(
        name="Progressive Gold",
        type=CivVItemType.tech,
        game_ids=[2, 18, 23, 33, 38, 48, 75],
        classification=ItemClassification.progression,
    ),
    "Progressive Happiness": CivVUsefulItemData(
        name="Progressive Happiness",
        type=CivVItemType.tech,
        game_ids=[6, 8, 15, 34, 51],
        classification=ItemClassification.progression,
    ),
    "Progressive Navy": CivVUsefulItemData(
        name="Progressive Navy",
        type=CivVItemType.tech,
        game_ids=[5, 12, 25, 31, 36, 49, 59, 68, 72],
        classification=ItemClassification.progression,
    ),
    "Progressive Melee Unit": CivVUsefulItemData(
        name="Progressive Melee Unit",
        type=CivVItemType.tech,
        game_ids=[11, 13, 20, 27, 30, 35, 39, 44, 45, 53, 63, 67, 69, 73, 77],
        classification=ItemClassification.progression,
    ),
    "Progressive Ranged Unit": CivVUsefulItemData(
        name="Progressive Ranged Unit",
        type=CivVItemType.tech,
        game_ids=[3, 28, 54, 57, 58, 62, 79],
        classification=ItemClassification.progression,
    ),
    "Progressive Siege Unit": CivVUsefulItemData(
        name="Progressive Siege Unit",
        type=CivVItemType.tech,
        game_ids=[14, 29, 40, 50, 61, 65],
        classification=ItemClassification.progression,
    ),
    "Progressive Misc": CivVUsefulItemData(
        name="Progressive Misc",
        type=CivVItemType.tech,
        game_ids=[9, 16, 21, 37, 55],
        classification=ItemClassification.progression,
    ),
}
"Dict of all progressive technologies"
