# %% IMPORTS
from .core import CivVLocationData
from .. import items
from ..enums import CivVLocationType

# All declaration
__all__ = [
    "BUILDING_LOCATIONS",
]


# %% LOCATION DECLARATIONS
# TODO: Add requirements to all locations
BUILDING_LOCATIONS = [
    CivVLocationData(
        name="Seaport",
        type=CivVLocationType.building,
        game_id=11,
        database_key_prefix="building_seaport",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Stable",
        type=CivVLocationType.building,
        game_id=12,
        database_key_prefix="building_stable",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Watermill",
        type=CivVLocationType.building,
        game_id=13,
        database_key_prefix="building_watermill",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Circus",
        type=CivVLocationType.building,
        game_id=14,
        database_key_prefix="building_circus",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Forge",
        type=CivVLocationType.building,
        game_id=15,
        database_key_prefix="building_forge",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Windmill",
        type=CivVLocationType.building,
        game_id=16,
        database_key_prefix="building_windmill",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Hydro Plant",
        type=CivVLocationType.building,
        game_id=17,
        database_key_prefix="building_hydro_plant",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Solar Plant",
        type=CivVLocationType.building,
        game_id=18,
        database_key_prefix="building_solar_plant",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Mint",
        type=CivVLocationType.building,
        game_id=19,
        database_key_prefix="building_mint",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Observatory",
        type=CivVLocationType.building,
        game_id=20,
        database_key_prefix="building_observatory",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Garden",
        type=CivVLocationType.building,
        game_id=22,
        database_key_prefix="building_garden",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Lighthouse",
        type=CivVLocationType.building,
        game_id=23,
        database_key_prefix="building_lighthouse",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Harbor",
        type=CivVLocationType.building,
        game_id=24,
        database_key_prefix="building_harbor",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Colosseum",
        type=CivVLocationType.building,
        game_id=25,
        database_key_prefix="building_colosseum",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Zoo",
        type=CivVLocationType.building,
        game_id=26,
        database_key_prefix="building_theatre",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Stadium",
        type=CivVLocationType.building,
        game_id=27,
        database_key_prefix="building_stadium",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Monument",
        type=CivVLocationType.building,
        game_id=28,
        database_key_prefix="building_monument",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Temple",
        type=CivVLocationType.building,
        game_id=29,
        database_key_prefix="building_temple",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Opera House",
        type=CivVLocationType.building,
        game_id=30,
        database_key_prefix="building_opera_house",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Museum",
        type=CivVLocationType.building,
        game_id=31,
        database_key_prefix="building_museum",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Broadcast Tower",
        type=CivVLocationType.building,
        game_id=32,
        database_key_prefix="building_broadcast_tower",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Barracks",
        type=CivVLocationType.building,
        game_id=33,
        database_key_prefix="building_barracks",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Armory",
        type=CivVLocationType.building,
        game_id=34,
        database_key_prefix="building_armory",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Military Academy",
        type=CivVLocationType.building,
        game_id=35,
        database_key_prefix="building_military_academy",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Arsenal",
        type=CivVLocationType.building,
        game_id=36,
        database_key_prefix="building_arsenal",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Walls",
        type=CivVLocationType.building,
        game_id=37,
        database_key_prefix="building_walls",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Castle",
        type=CivVLocationType.building,
        game_id=38,
        database_key_prefix="building_castle",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Military Base",
        type=CivVLocationType.building,
        game_id=39,
        database_key_prefix="building_military_base",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Granary",
        type=CivVLocationType.building,
        game_id=40,
        database_key_prefix="building_granary",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Hospital",
        type=CivVLocationType.building,
        game_id=41,
        database_key_prefix="building_hospital",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Medical Lab",
        type=CivVLocationType.building,
        game_id=42,
        database_key_prefix="building_medical_lab",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Workshop",
        type=CivVLocationType.building,
        game_id=43,
        database_key_prefix="building_workshop",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Factory",
        type=CivVLocationType.building,
        game_id=44,
        database_key_prefix="building_factory",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Nuclear Plant",
        type=CivVLocationType.building,
        game_id=45,
        database_key_prefix="building_nuclear_plant",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Spaceship Factory",
        type=CivVLocationType.building,
        game_id=46,
        database_key_prefix="building_spaceship_factory",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Market",
        type=CivVLocationType.building,
        game_id=47,
        database_key_prefix="building_market",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Bank",
        type=CivVLocationType.building,
        game_id=48,
        database_key_prefix="building_bank",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Stock Exchange",
        type=CivVLocationType.building,
        game_id=49,
        database_key_prefix="building_stock_exchange",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Library",
        type=CivVLocationType.building,
        game_id=50,
        database_key_prefix="building_library",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="University",
        type=CivVLocationType.building,
        game_id=51,
        database_key_prefix="building_university",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Public School",
        type=CivVLocationType.building,
        game_id=52,
        database_key_prefix="building_public_school",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Laboratory",
        type=CivVLocationType.building,
        game_id=53,
        database_key_prefix="building_laboratory",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Aqueduct",
        type=CivVLocationType.building,
        game_id=91,
        database_key_prefix="building_aqueduct",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Stone Works",
        type=CivVLocationType.building,
        game_id=92,
        database_key_prefix="building_stone_works",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Amphitheater",
        type=CivVLocationType.building,
        game_id=121,
        database_key_prefix="building_amphitheater",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Shrine",
        type=CivVLocationType.building,
        game_id=122,
        database_key_prefix="building_shrine",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Recycling Center",
        type=CivVLocationType.building,
        game_id=123,
        database_key_prefix="building_recycling_center",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Bomb Shelter",
        type=CivVLocationType.building,
        game_id=124,
        database_key_prefix="building_bomb_shelter",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Constabulary",
        type=CivVLocationType.building,
        game_id=125,
        database_key_prefix="building_constable",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Police Station",
        type=CivVLocationType.building,
        game_id=126,
        database_key_prefix="building_police_station",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Hotel",
        type=CivVLocationType.building,
        game_id=151,
        database_key_prefix="building_hotel",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Caravansary",
        type=CivVLocationType.building,
        game_id=152,
        database_key_prefix="building_caravansary",
        requirements=items.ItemRequirements(
        )
    ),
    CivVLocationData(
        name="Airport",
        type=CivVLocationType.building,
        game_id=153,
        database_key_prefix="building_airport",
        requirements=items.ItemRequirements(
        )
    ),
]
"List of all standard building locations"
