# %% IMPORTS
from .core import CivVLocationData
from .. import regions
from ..enums import CivVLocationType

# All declaration
__all__ = [
    "POLICY_BRANCH_LOCATIONS",
    "POLICY_LOCATIONS",
]


# %% LOCATION DECLARATIONS
POLICY_BRANCH_LOCATIONS = [
    # All vanilla policy branches
    CivVLocationData(
        name="Tradition",
        type=CivVLocationType.policy_branch,
        game_id=0,
        database_key_prefix="policy_branch_tradition",
        region=regions.ANCIENT_ERA_POLICY,
    ),
    CivVLocationData(
        name="Liberty", 
        type=CivVLocationType.policy_branch, 
        game_id=1, 
        database_key_prefix="policy_branch_liberty", 
        region=regions.CLASSICAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Honor", 
        type=CivVLocationType.policy_branch, 
        game_id=2, 
        database_key_prefix="policy_branch_honor", 
        region=regions.MEDIEVAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Piety", 
        type=CivVLocationType.policy_branch, 
        game_id=3, 
        database_key_prefix="policy_branch_piety", 
        region=regions.RENAISSANCE_ERA_POLICY,
    ),
    CivVLocationData(
        name="Patronage", 
        type=CivVLocationType.policy_branch, 
        game_id=4, 
        database_key_prefix="policy_branch_patronage", 
        region=regions.INDUSTRIAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Aesthetics", 
        type=CivVLocationType.policy_branch, 
        game_id=5, 
        database_key_prefix="policy_branch_aesthetics", 
        region=regions.MODERN_ERA_POLICY,
    ),
    CivVLocationData(
        name="Commerce", 
        type=CivVLocationType.policy_branch, 
        game_id=6, 
        database_key_prefix="policy_branch_commerce", 
        region=regions.ATOMIC_ERA_POLICY,
    ),
    CivVLocationData(
        name="Exploration", 
        type=CivVLocationType.policy_branch, 
        game_id=7, 
        database_key_prefix="policy_branch_exploration", 
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Rationalism", 
        type=CivVLocationType.policy_branch, 
        game_id=8, 
        database_key_prefix="policy_branch_rationalism", 
        region=regions.INFORMATION_ERA_POLICY,
    ),

    # Policy branch finishers masked as policy branches
    CivVLocationData(
        name="Tradition Finished", 
        type=CivVLocationType.policy_branch, 
        game_id=12, 
        database_key_prefix="policy_branch_tradition_finisher", 
        region=regions.ANCIENT_ERA_POLICY,
    ),
    CivVLocationData(
        name="Liberty Finished", 
        type=CivVLocationType.policy_branch, 
        game_id=13, 
        database_key_prefix="policy_branch_liberty_finisher", 
        region=regions.CLASSICAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Honor Finished",
        type=CivVLocationType.policy_branch, 
        game_id=14, 
        database_key_prefix="policy_branch_honor_finisher", 
        region=regions.MEDIEVAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Piety Finished", 
        type=CivVLocationType.policy_branch, 
        game_id=15, 
        database_key_prefix="policy_branch_piety_finisher", 
        region=regions.RENAISSANCE_ERA_POLICY,
    ),
    CivVLocationData(
        name="Patronage Finished", 
        type=CivVLocationType.policy_branch, 
        game_id=16, 
        database_key_prefix="policy_branch_patronage_finisher", 
        region=regions.INDUSTRIAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Aesthetics Finished", 
        type=CivVLocationType.policy_branch, 
        game_id=17, 
        database_key_prefix="policy_branch_aesthetics_finisher", 
        region=regions.MODERN_ERA_POLICY,
    ),
    CivVLocationData(
        name="Commerce Finished", 
        type=CivVLocationType.policy_branch, 
        game_id=18, 
        database_key_prefix="policy_branch_commerce_finisher", 
        region=regions.ATOMIC_ERA_POLICY,
    ),
    CivVLocationData(
        name="Exploration Finished", 
        type=CivVLocationType.policy_branch, 
        game_id=19, 
        database_key_prefix="policy_branch_exploration_finisher", 
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Rationalism Finished", 
        type=CivVLocationType.policy_branch, 
        game_id=20, 
        database_key_prefix="policy_branch_rationalism_finisher", 
        region=regions.INFORMATION_ERA_POLICY,
    ),
]
"List of all policy branch locations"


POLICY_LOCATIONS = [
    # All vanilla policies converted to AP policies
    CivVLocationData(
        name="Tradition AP 1", 
        type=CivVLocationType.policy, 
        game_id=111, 
        database_key_prefix="policy_tradition_ap1", 
        region=regions.ANCIENT_ERA_POLICY,
    ),
    CivVLocationData(
        name="Tradition AP 2", 
        type=CivVLocationType.policy, 
        game_id=112, 
        database_key_prefix="policy_tradition_ap2", 
        region=regions.ANCIENT_ERA_POLICY,
    ),
    CivVLocationData(
        name="Tradition AP 3",
        type=CivVLocationType.policy,
        game_id=113,
        database_key_prefix="policy_tradition_ap3",
        region=regions.ANCIENT_ERA_POLICY,
    ),
    CivVLocationData(
        name="Tradition AP 4",
        type=CivVLocationType.policy,
        game_id=114,
        database_key_prefix="policy_tradition_ap4",
        region=regions.ANCIENT_ERA_POLICY,
    ),
    CivVLocationData(
        name="Tradition AP 5",
        type=CivVLocationType.policy,
        game_id=115,
        database_key_prefix="policy_tradition_ap5",
        region=regions.ANCIENT_ERA_POLICY,
    ),
    CivVLocationData(
        name="Liberty AP 1",
        type=CivVLocationType.policy,
        game_id=116,
        database_key_prefix="policy_liberty_ap1",
        region=regions.CLASSICAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Liberty AP 2",
        type=CivVLocationType.policy,
        game_id=117,
        database_key_prefix="policy_liberty_ap2",
        region=regions.CLASSICAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Liberty AP 3",
        type=CivVLocationType.policy,
        game_id=118,
        database_key_prefix="policy_liberty_ap3",
        region=regions.CLASSICAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Liberty AP 4",
        type=CivVLocationType.policy,
        game_id=119,
        database_key_prefix="policy_liberty_ap4",
        region=regions.CLASSICAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Liberty AP 5",
        type=CivVLocationType.policy,
        game_id=120,
        database_key_prefix="policy_liberty_ap5",
        region=regions.CLASSICAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Honor AP 1",
        type=CivVLocationType.policy,
        game_id=121,
        database_key_prefix="policy_honor_ap1",
        region=regions.MEDIEVAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Honor AP 2",
        type=CivVLocationType.policy,
        game_id=122,
        database_key_prefix="policy_honor_ap2",
        region=regions.MEDIEVAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Honor AP 3",
        type=CivVLocationType.policy,
        game_id=123,
        database_key_prefix="policy_honor_ap3",
        region=regions.MEDIEVAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Honor AP 4",
        type=CivVLocationType.policy,
        game_id=124,
        database_key_prefix="policy_honor_ap4",
        region=regions.MEDIEVAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Honor AP 5",
        type=CivVLocationType.policy,
        game_id=125,
        database_key_prefix="policy_honor_ap5",
        region=regions.MEDIEVAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Piety AP 1",
        type=CivVLocationType.policy,
        game_id=126,
        database_key_prefix="policy_piety_ap1",
        region=regions.RENAISSANCE_ERA_POLICY,
    ),
    CivVLocationData(
        name="Piety AP 2",
        type=CivVLocationType.policy,
        game_id=127,
        database_key_prefix="policy_piety_ap2",
        region=regions.RENAISSANCE_ERA_POLICY,
    ),
    CivVLocationData(
        name="Piety AP 3",
        type=CivVLocationType.policy,
        game_id=128,
        database_key_prefix="policy_piety_ap3",
        region=regions.RENAISSANCE_ERA_POLICY,
    ),
    CivVLocationData(
        name="Piety AP 4",
        type=CivVLocationType.policy,
        game_id=129,
        database_key_prefix="policy_piety_ap4",
        region=regions.RENAISSANCE_ERA_POLICY,
    ),
    CivVLocationData(
        name="Piety AP 5",
        type=CivVLocationType.policy,
        game_id=130,
        database_key_prefix="policy_piety_ap5",
        region=regions.RENAISSANCE_ERA_POLICY,
    ),
    CivVLocationData(
        name="Patronage AP 1",
        type=CivVLocationType.policy,
        game_id=131,
        database_key_prefix="policy_patronage_ap1",
        region=regions.INDUSTRIAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Patronage AP 2",
        type=CivVLocationType.policy,
        game_id=132,
        database_key_prefix="policy_patronage_ap2",
        region=regions.INDUSTRIAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Patronage AP 3",
        type=CivVLocationType.policy,
        game_id=133,
        database_key_prefix="policy_patronage_ap3",
        region=regions.INDUSTRIAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Patronage AP 4",
        type=CivVLocationType.policy,
        game_id=134,
        database_key_prefix="policy_patronage_ap4",
        region=regions.INDUSTRIAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Patronage AP 5",
        type=CivVLocationType.policy,
        game_id=135,
        database_key_prefix="policy_patronage_ap5",
        region=regions.INDUSTRIAL_ERA_POLICY,
    ),
    CivVLocationData(
        name="Aesthetics AP 1",
        type=CivVLocationType.policy,
        game_id=136,
        database_key_prefix="policy_aesthetics_ap1",
        region=regions.MODERN_ERA_POLICY,
    ),
    CivVLocationData(
        name="Aesthetics AP 2",
        type=CivVLocationType.policy,
        game_id=137,
        database_key_prefix="policy_aesthetics_ap2",
        region=regions.MODERN_ERA_POLICY,
    ),
    CivVLocationData(
        name="Aesthetics AP 3",
        type=CivVLocationType.policy,
        game_id=138,
        database_key_prefix="policy_aesthetics_ap3",
        region=regions.MODERN_ERA_POLICY,
    ),
    CivVLocationData(
        name="Aesthetics AP 4",
        type=CivVLocationType.policy,
        game_id=139,
        database_key_prefix="policy_aesthetics_ap4",
        region=regions.MODERN_ERA_POLICY,
    ),
    CivVLocationData(
        name="Aesthetics AP 5",
        type=CivVLocationType.policy,
        game_id=140,
        database_key_prefix="policy_aesthetics_ap5",
        region=regions.MODERN_ERA_POLICY,
    ),
    CivVLocationData(
        name="Commerce AP 1",
        type=CivVLocationType.policy,
        game_id=141,
        database_key_prefix="policy_commerce_ap1",
        region=regions.ATOMIC_ERA_POLICY,
    ),
    CivVLocationData(
        name="Commerce AP 2",
        type=CivVLocationType.policy,
        game_id=142,
        database_key_prefix="policy_commerce_ap2",
        region=regions.ATOMIC_ERA_POLICY,
    ),
    CivVLocationData(
        name="Commerce AP 3",
        type=CivVLocationType.policy,
        game_id=143,
        database_key_prefix="policy_commerce_ap3",
        region=regions.ATOMIC_ERA_POLICY,
    ),
    CivVLocationData(
        name="Commerce AP 4",
        type=CivVLocationType.policy,
        game_id=144,
        database_key_prefix="policy_commerce_ap4",
        region=regions.ATOMIC_ERA_POLICY,
    ),
    CivVLocationData(
        name="Commerce AP 5",
        type=CivVLocationType.policy,
        game_id=145,
        database_key_prefix="policy_commerce_ap5",
        region=regions.ATOMIC_ERA_POLICY,
    ),
    CivVLocationData(
        name="Exploration AP 1",
        type=CivVLocationType.policy,
        game_id=146,
        database_key_prefix="policy_exploration_ap1",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Exploration AP 2",
        type=CivVLocationType.policy,
        game_id=147,
        database_key_prefix="policy_exploration_ap2",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Exploration AP 3",
        type=CivVLocationType.policy,
        game_id=148,
        database_key_prefix="policy_exploration_ap3",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Exploration AP 4",
        type=CivVLocationType.policy,
        game_id=149,
        database_key_prefix="policy_exploration_ap4",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Exploration AP 5",
        type=CivVLocationType.policy,
        game_id=150,
        database_key_prefix="policy_exploration_ap5",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Rationalism AP 1",
        type=CivVLocationType.policy,
        game_id=151,
        database_key_prefix="policy_rationalism_ap1",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Rationalism AP 2",
        type=CivVLocationType.policy,
        game_id=152,
        database_key_prefix="policy_rationalism_ap2",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Rationalism AP 3",
        type=CivVLocationType.policy,
        game_id=153,
        database_key_prefix="policy_rationalism_ap3",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Rationalism AP 4",
        type=CivVLocationType.policy,
        game_id=154,
        database_key_prefix="policy_rationalism_ap4",
        region=regions.INFORMATION_ERA_POLICY,
    ),
    CivVLocationData(
        name="Rationalism AP 5", 
        type=CivVLocationType.policy,
        game_id=155,
        database_key_prefix="policy_rationalism_ap5",
        region=regions.INFORMATION_ERA_POLICY,
    ),
]
"List of all policy locations"
