# %% IMPORTS
from .core import CivVLocationData
from ..requirements import (
    ARCHER_CLASS,
    ARMOR_CLASS,
    ARMORY,
    BARRACKS,
    BOMBER_CLASS,
    CARRIER_CLASS,
    FIGHTER_CLASS,
    GUN_CLASS,
    HELICOPTER_CLASS,
    MELEE_CLASS,
    MILITARY_ACADEMY,
    MOUNTED_CLASS,
    NAVAL_MELEE_CLASS,
    NAVAL_RANGED_CLASS,
    RECON_CLASS,
    SIEGE_CLASS,
    SUBMARINE_CLASS,
)
from ..enums import CivVLocationType

# All declaration
__all__ = [
    "PROMOTION_LOCATIONS",
]


# %% LOCATION DECLARATIONS
PROMOTION_LOCATIONS = [
    CivVLocationData(
        name="Archer AP A1",
        type=CivVLocationType.promotion,
        game_id=229,
        database_key_prefix="promotion_archer_ap_a1",
        requirements=ARCHER_CLASS,
    ),
    CivVLocationData(
        name="Archer AP A2",
        type=CivVLocationType.promotion,
        game_id=230,
        database_key_prefix="promotion_archer_ap_a2",
        requirements=BARRACKS & ARCHER_CLASS,
    ),
    CivVLocationData(
        name="Archer AP A3",
        type=CivVLocationType.promotion,
        game_id=231,
        database_key_prefix="promotion_archer_ap_a3",
        requirements=ARMORY & ARCHER_CLASS,
    ),
    CivVLocationData(
        name="Archer AP A4",
        type=CivVLocationType.promotion,
        game_id=232,
        database_key_prefix="promotion_archer_ap_a4",
        requirements=MILITARY_ACADEMY & ARCHER_CLASS,
    ),
    CivVLocationData(
        name="Archer AP B1",
        type=CivVLocationType.promotion,
        game_id=233,
        database_key_prefix="promotion_archer_ap_b1",
        requirements=ARCHER_CLASS,
    ),
    CivVLocationData(
        name="Archer AP B2",
        type=CivVLocationType.promotion,
        game_id=234,
        database_key_prefix="promotion_archer_ap_b2",
        requirements=BARRACKS & ARCHER_CLASS,
    ),
    CivVLocationData(
        name="Archer AP B3",
        type=CivVLocationType.promotion,
        game_id=235,
        database_key_prefix="promotion_archer_ap_b3",
        requirements=ARMORY & ARCHER_CLASS,
    ),
    CivVLocationData(
        name="Armor AP A1",
        type=CivVLocationType.promotion,
        game_id=236,
        database_key_prefix="promotion_armor_ap_a1",
        requirements=ARMOR_CLASS,
    ),
    CivVLocationData(
        name="Armor AP A2",
        type=CivVLocationType.promotion,
        game_id=237,
        database_key_prefix="promotion_armor_ap_a2",
        requirements=BARRACKS & ARMOR_CLASS,
    ),
    CivVLocationData(
        name="Armor AP A3",
        type=CivVLocationType.promotion,
        game_id=238,
        database_key_prefix="promotion_armor_ap_a3",
        requirements=ARMORY & ARMOR_CLASS,
    ),
    CivVLocationData(
        name="Armor AP A4",
        type=CivVLocationType.promotion,
        game_id=239,
        database_key_prefix="promotion_armor_ap_a4",
        requirements=MILITARY_ACADEMY & ARMOR_CLASS,
    ),
    CivVLocationData(
        name="Armor AP B1",
        type=CivVLocationType.promotion,
        game_id=240,
        database_key_prefix="promotion_armor_ap_b1",
        requirements=ARMOR_CLASS,
    ),
    CivVLocationData(
        name="Armor AP B2",
        type=CivVLocationType.promotion,
        game_id=241,
        database_key_prefix="promotion_armor_ap_b2",
        requirements=BARRACKS & ARMOR_CLASS,
    ),
    CivVLocationData(
        name="Armor AP B3",
        type=CivVLocationType.promotion,
        game_id=242,
        database_key_prefix="promotion_armor_ap_b3",
        requirements=ARMORY & ARMOR_CLASS,
    ),
    CivVLocationData(
        name="Bomber AP A1",
        type=CivVLocationType.promotion,
        game_id=243,
        database_key_prefix="promotion_bomber_ap_a1",
        requirements=BOMBER_CLASS,
    ),
    CivVLocationData(
        name="Bomber AP A2",
        type=CivVLocationType.promotion,
        game_id=244,
        database_key_prefix="promotion_bomber_ap_a2",
        requirements=BARRACKS & BOMBER_CLASS,
    ),
    CivVLocationData(
        name="Bomber AP A3",
        type=CivVLocationType.promotion,
        game_id=245,
        database_key_prefix="promotion_bomber_ap_a3",
        requirements=ARMORY & BOMBER_CLASS,
    ),
    CivVLocationData(
        name="Bomber AP A4",
        type=CivVLocationType.promotion,
        game_id=246,
        database_key_prefix="promotion_bomber_ap_a4",
        requirements=MILITARY_ACADEMY & BOMBER_CLASS,
    ),
    CivVLocationData(
        name="Bomber AP B1",
        type=CivVLocationType.promotion,
        game_id=247,
        database_key_prefix="promotion_bomber_ap_b1",
        requirements=BOMBER_CLASS,
    ),
    CivVLocationData(
        name="Bomber AP B2",
        type=CivVLocationType.promotion,
        game_id=248,
        database_key_prefix="promotion_bomber_ap_b2",
        requirements=BARRACKS & BOMBER_CLASS,
    ),
    CivVLocationData(
        name="Bomber AP B3",
        type=CivVLocationType.promotion,
        game_id=249,
        database_key_prefix="promotion_bomber_ap_b3",
        requirements=ARMORY & BOMBER_CLASS,
    ),
    CivVLocationData(
        name="Carrier AP A1",
        type=CivVLocationType.promotion,
        game_id=250,
        database_key_prefix="promotion_carrier_ap_a1",
        requirements=CARRIER_CLASS,
    ),
    CivVLocationData(
        name="Carrier AP A2",
        type=CivVLocationType.promotion,
        game_id=251,
        database_key_prefix="promotion_carrier_ap_a2",
        requirements=BARRACKS & CARRIER_CLASS,
    ),
    CivVLocationData(
        name="Carrier AP A3",
        type=CivVLocationType.promotion,
        game_id=252,
        database_key_prefix="promotion_carrier_ap_a3",
        requirements=ARMORY & CARRIER_CLASS,
    ),
    CivVLocationData(
        name="Fighter AP A1",
        type=CivVLocationType.promotion,
        game_id=253,
        database_key_prefix="promotion_fighter_ap_a1",
        requirements=FIGHTER_CLASS,
    ),
    CivVLocationData(
        name="Fighter AP A2",
        type=CivVLocationType.promotion,
        game_id=254,
        database_key_prefix="promotion_fighter_ap_a2",
        requirements=BARRACKS & FIGHTER_CLASS,
    ),
    CivVLocationData(
        name="Fighter AP A3",
        type=CivVLocationType.promotion,
        game_id=255,
        database_key_prefix="promotion_fighter_ap_a3",
        requirements=ARMORY & FIGHTER_CLASS,
    ),
    CivVLocationData(
        name="Fighter AP A4",
        type=CivVLocationType.promotion,
        game_id=256,
        database_key_prefix="promotion_fighter_ap_a4",
        requirements=MILITARY_ACADEMY & FIGHTER_CLASS,
    ),
    CivVLocationData(
        name="Fighter AP B1",
        type=CivVLocationType.promotion,
        game_id=257,
        database_key_prefix="promotion_fighter_ap_b1",
        requirements=FIGHTER_CLASS,
    ),
    CivVLocationData(
        name="Fighter AP B2",
        type=CivVLocationType.promotion,
        game_id=258,
        database_key_prefix="promotion_fighter_ap_b2",
        requirements=BARRACKS & FIGHTER_CLASS,
    ),
    CivVLocationData(
        name="Fighter AP B3",
        type=CivVLocationType.promotion,
        game_id=259,
        database_key_prefix="promotion_fighter_ap_b3",
        requirements=ARMORY & FIGHTER_CLASS,
    ),
    CivVLocationData(
        name="Gun AP A1",
        type=CivVLocationType.promotion,
        game_id=260,
        database_key_prefix="promotion_gun_ap_a1",
        requirements=GUN_CLASS,
    ),
    CivVLocationData(
        name="Gun AP A2",
        type=CivVLocationType.promotion,
        game_id=261,
        database_key_prefix="promotion_gun_ap_a2",
        requirements=BARRACKS & GUN_CLASS,
    ),
    CivVLocationData(
        name="Gun AP A3",
        type=CivVLocationType.promotion,
        game_id=262,
        database_key_prefix="promotion_gun_ap_a3",
        requirements=ARMORY & GUN_CLASS,
    ),
    CivVLocationData(
        name="Gun AP A4",
        type=CivVLocationType.promotion,
        game_id=263,
        database_key_prefix="promotion_gun_ap_a4",
        requirements=MILITARY_ACADEMY & GUN_CLASS,
    ),
    CivVLocationData(
        name="Gun AP B1",
        type=CivVLocationType.promotion,
        game_id=264,
        database_key_prefix="promotion_gun_ap_b1",
        requirements=GUN_CLASS,
    ),
    CivVLocationData(
        name="Gun AP B2",
        type=CivVLocationType.promotion,
        game_id=265,
        database_key_prefix="promotion_gun_ap_b2",
        requirements=BARRACKS & GUN_CLASS,
    ),
    CivVLocationData(
        name="Gun AP B3",
        type=CivVLocationType.promotion,
        game_id=266,
        database_key_prefix="promotion_gun_ap_b3",
        requirements=ARMORY & GUN_CLASS,
    ),
    CivVLocationData(
        name="Helicopter AP A1",
        type=CivVLocationType.promotion,
        game_id=267,
        database_key_prefix="promotion_helicopter_ap_a1",
        requirements=HELICOPTER_CLASS,
    ),
    CivVLocationData(
        name="Helicopter AP A2",
        type=CivVLocationType.promotion,
        game_id=268,
        database_key_prefix="promotion_helicopter_ap_a2",
        requirements=BARRACKS & HELICOPTER_CLASS,
    ),
    CivVLocationData(
        name="Helicopter AP A3",
        type=CivVLocationType.promotion,
        game_id=269,
        database_key_prefix="promotion_helicopter_ap_a3",
        requirements=ARMORY & HELICOPTER_CLASS,
    ),
    CivVLocationData(
        name="Melee AP A1",
        type=CivVLocationType.promotion,
        game_id=270,
        database_key_prefix="promotion_melee_ap_a1",
        requirements=MELEE_CLASS,
    ),
    CivVLocationData(
        name="Melee AP A2",
        type=CivVLocationType.promotion,
        game_id=271,
        database_key_prefix="promotion_melee_ap_a2",
        requirements=BARRACKS & MELEE_CLASS,
    ),
    CivVLocationData(
        name="Melee AP A3",
        type=CivVLocationType.promotion,
        game_id=272,
        database_key_prefix="promotion_melee_ap_a3",
        requirements=ARMORY & MELEE_CLASS,
    ),
    CivVLocationData(
        name="Melee AP A4",
        type=CivVLocationType.promotion,
        game_id=273,
        database_key_prefix="promotion_melee_ap_a4",
        requirements=MILITARY_ACADEMY & MELEE_CLASS,
    ),
    CivVLocationData(
        name="Melee AP B1",
        type=CivVLocationType.promotion,
        game_id=274,
        database_key_prefix="promotion_melee_ap_b1",
        requirements=MELEE_CLASS,
    ),
    CivVLocationData(
        name="Melee AP B2",
        type=CivVLocationType.promotion,
        game_id=275,
        database_key_prefix="promotion_melee_ap_b2",
        requirements=BARRACKS & MELEE_CLASS,
    ),
    CivVLocationData(
        name="Melee AP B3",
        type=CivVLocationType.promotion,
        game_id=276,
        database_key_prefix="promotion_melee_ap_b3",
        requirements=ARMORY & MELEE_CLASS,
    ),
    CivVLocationData(
        name="Mounted AP A1",
        type=CivVLocationType.promotion,
        game_id=277,
        database_key_prefix="promotion_mounted_ap_a1",
        requirements=MOUNTED_CLASS,
    ),
    CivVLocationData(
        name="Mounted AP A2",
        type=CivVLocationType.promotion,
        game_id=278,
        database_key_prefix="promotion_mounted_ap_a2",
        requirements=BARRACKS & MOUNTED_CLASS,
    ),
    CivVLocationData(
        name="Mounted AP A3",
        type=CivVLocationType.promotion,
        game_id=279,
        database_key_prefix="promotion_mounted_ap_a3",
        requirements=ARMORY & MOUNTED_CLASS,
    ),
    CivVLocationData(
        name="Mounted AP A4",
        type=CivVLocationType.promotion,
        game_id=280,
        database_key_prefix="promotion_mounted_ap_a4",
        requirements=MILITARY_ACADEMY & MOUNTED_CLASS,
    ),
    CivVLocationData(
        name="Mounted AP B1",
        type=CivVLocationType.promotion,
        game_id=281,
        database_key_prefix="promotion_mounted_ap_b1",
        requirements=MOUNTED_CLASS,
    ),
    CivVLocationData(
        name="Mounted AP B2",
        type=CivVLocationType.promotion,
        game_id=282,
        database_key_prefix="promotion_mounted_ap_b2",
        requirements=BARRACKS & MOUNTED_CLASS,
    ),
    CivVLocationData(
        name="Mounted AP B3",
        type=CivVLocationType.promotion,
        game_id=283,
        database_key_prefix="promotion_mounted_ap_b3",
        requirements=ARMORY & MOUNTED_CLASS,
    ),
    CivVLocationData(
        name="Naval Melee AP A1",
        type=CivVLocationType.promotion,
        game_id=284,
        database_key_prefix="promotion_naval_melee_ap_a1",
        requirements=NAVAL_MELEE_CLASS,
    ),
    CivVLocationData(
        name="Naval Melee AP A2",
        type=CivVLocationType.promotion,
        game_id=285,
        database_key_prefix="promotion_naval_melee_ap_a2",
        requirements=BARRACKS & NAVAL_MELEE_CLASS,
    ),
    CivVLocationData(
        name="Naval Melee AP A3",
        type=CivVLocationType.promotion,
        game_id=286,
        database_key_prefix="promotion_naval_melee_ap_a3",
        requirements=ARMORY & NAVAL_MELEE_CLASS,
    ),
    CivVLocationData(
        name="Naval Melee AP A4",
        type=CivVLocationType.promotion,
        game_id=287,
        database_key_prefix="promotion_naval_melee_ap_a4",
        requirements=MILITARY_ACADEMY & NAVAL_MELEE_CLASS,
    ),
    CivVLocationData(
        name="Naval Melee AP B1",
        type=CivVLocationType.promotion,
        game_id=288,
        database_key_prefix="promotion_naval_melee_ap_b1",
        requirements=NAVAL_MELEE_CLASS,
    ),
    CivVLocationData(
        name="Naval Melee AP B2",
        type=CivVLocationType.promotion,
        game_id=289,
        database_key_prefix="promotion_naval_melee_ap_b2",
        requirements=BARRACKS & NAVAL_MELEE_CLASS,
    ),
    CivVLocationData(
        name="Naval Melee AP B3",
        type=CivVLocationType.promotion,
        game_id=290,
        database_key_prefix="promotion_naval_melee_ap_b3",
        requirements=ARMORY & NAVAL_MELEE_CLASS,
    ),
    CivVLocationData(
        name="Naval_Ranged AP A1",
        type=CivVLocationType.promotion,
        game_id=291,
        database_key_prefix="promotion_naval_ranged_ap_a1",
        requirements=NAVAL_RANGED_CLASS,
    ),
    CivVLocationData(
        name="Naval Ranged AP A2",
        type=CivVLocationType.promotion,
        game_id=292,
        database_key_prefix="promotion_naval_ranged_ap_a2",
        requirements=BARRACKS & NAVAL_RANGED_CLASS,
    ),
    CivVLocationData(
        name="Naval Ranged AP A3",
        type=CivVLocationType.promotion,
        game_id=293,
        database_key_prefix="promotion_naval_ranged_ap_a3",
        requirements=ARMORY & NAVAL_RANGED_CLASS,
    ),
    CivVLocationData(
        name="Naval Ranged AP A4",
        type=CivVLocationType.promotion,
        game_id=294,
        database_key_prefix="promotion_naval_ranged_ap_a4",
        requirements=MILITARY_ACADEMY & NAVAL_RANGED_CLASS,
    ),
    CivVLocationData(
        name="Naval Ranged AP B1",
        type=CivVLocationType.promotion,
        game_id=295,
        database_key_prefix="promotion_naval_ranged_ap_b1",
        requirements=NAVAL_RANGED_CLASS,
    ),
    CivVLocationData(
        name="Naval Ranged AP B2",
        type=CivVLocationType.promotion,
        game_id=296,
        database_key_prefix="promotion_naval_ranged_ap_b2",
        requirements=BARRACKS & NAVAL_RANGED_CLASS,
    ),
    CivVLocationData(
        name="Naval Ranged AP B3",
        type=CivVLocationType.promotion,
        game_id=297,
        database_key_prefix="promotion_naval_ranged_ap_b3",
        requirements=ARMORY & NAVAL_RANGED_CLASS,
    ),
    CivVLocationData(
        name="Recon AP A1",
        type=CivVLocationType.promotion,
        game_id=298,
        database_key_prefix="promotion_recon_ap_a1",
        requirements=RECON_CLASS,
    ),
    CivVLocationData(
        name="Recon AP A2",
        type=CivVLocationType.promotion,
        game_id=299,
        database_key_prefix="promotion_recon_ap_a2",
        requirements=BARRACKS & RECON_CLASS,
    ),
    CivVLocationData(
        name="Recon AP A3",
        type=CivVLocationType.promotion,
        game_id=300,
        database_key_prefix="promotion_recon_ap_a3",
        requirements=ARMORY & RECON_CLASS,
    ),
    CivVLocationData(
        name="Siege AP A1",
        type=CivVLocationType.promotion,
        game_id=301,
        database_key_prefix="promotion_siege_ap_a1",
        requirements=SIEGE_CLASS,
    ),
    CivVLocationData(
        name="Siege AP A2",
        type=CivVLocationType.promotion,
        game_id=302,
        database_key_prefix="promotion_siege_ap_a2",
        requirements=BARRACKS & SIEGE_CLASS,
    ),
    CivVLocationData(
        name="Siege AP A3",
        type=CivVLocationType.promotion,
        game_id=303,
        database_key_prefix="promotion_siege_ap_a3",
        requirements=ARMORY & SIEGE_CLASS,
    ),
    CivVLocationData(
        name="Siege AP A4",
        type=CivVLocationType.promotion,
        game_id=304,
        database_key_prefix="promotion_siege_ap_a4",
        requirements=MILITARY_ACADEMY & SIEGE_CLASS,
    ),
    CivVLocationData(
        name="Siege AP B1",
        type=CivVLocationType.promotion,
        game_id=305,
        database_key_prefix="promotion_siege_ap_b1",
        requirements=SIEGE_CLASS,
    ),
    CivVLocationData(
        name="Siege AP B2",
        type=CivVLocationType.promotion,
        game_id=306,
        database_key_prefix="promotion_siege_ap_b2",
        requirements=BARRACKS & SIEGE_CLASS,
    ),
    CivVLocationData(
        name="Siege AP B3",
        type=CivVLocationType.promotion,
        game_id=307,
        database_key_prefix="promotion_siege_ap_b3",
        requirements=ARMORY & SIEGE_CLASS,
    ),
    CivVLocationData(
        name="Submarine AP A1",
        type=CivVLocationType.promotion,
        game_id=308,
        database_key_prefix="promotion_submarine_ap_a1",
        requirements=SUBMARINE_CLASS,
    ),
    CivVLocationData(
        name="Submarine AP A2",
        type=CivVLocationType.promotion,
        game_id=309,
        database_key_prefix="promotion_submarine_ap_a2",
        requirements=BARRACKS & SUBMARINE_CLASS,
    ),
    CivVLocationData(
        name="Submarine AP A3",
        type=CivVLocationType.promotion,
        game_id=310,
        database_key_prefix="promotion_submarine_ap_a3",
        requirements=ARMORY & SUBMARINE_CLASS,
    ),
    CivVLocationData(
        name="Submarine AP A4",
        type=CivVLocationType.promotion,
        game_id=311,
        database_key_prefix="promotion_submarine_ap_a4",
        requirements=MILITARY_ACADEMY & SUBMARINE_CLASS,
    ),
]
"List of all promotion locations"
