# %% IMPORTS
from .core import CivVLocationData
from .. import regions
from ..enums import CivVLocationType

# All declaration
__all__ = [
    "SETTLER_LOCATIONS",
]

# %% LOCATION DECLARATIONS
SETTLER_LOCATIONS = [
    CivVLocationData(
        name="Settler #1",
        type=CivVLocationType.settler,
        game_id=1,
        database_key_prefix="settler1",
        region=regions.ANCIENT_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #2",
        type=CivVLocationType.settler,
        game_id=2,
        database_key_prefix="settler2",
        region=regions.CLASSICAL_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #3",
        type=CivVLocationType.settler,
        game_id=3,
        database_key_prefix="settler3",
        region=regions.CLASSICAL_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #4",
        type=CivVLocationType.settler,
        game_id=4,
        database_key_prefix="settler4",
        region=regions.MEDIEVAL_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #5",
        type=CivVLocationType.settler,
        game_id=5,
        database_key_prefix="settler5",
        region=regions.MEDIEVAL_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #6",
        type=CivVLocationType.settler,
        game_id=6,
        database_key_prefix="settler6",
        region=regions.RENAISSANCE_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #7",
        type=CivVLocationType.settler,
        game_id=7,
        database_key_prefix="settler7",
        region=regions.RENAISSANCE_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #8",
        type=CivVLocationType.settler,
        game_id=8,
        database_key_prefix="settler8",
        region=regions.INDUSTRIAL_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #9",
        type=CivVLocationType.settler,
        game_id=9,
        database_key_prefix="settler9",
        region=regions.INDUSTRIAL_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #10",
        type=CivVLocationType.settler,
        game_id=10,
        database_key_prefix="settler10",
        region=regions.INDUSTRIAL_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #11",
        type=CivVLocationType.settler,
        game_id=11,
        database_key_prefix="settler11",
        region=regions.MODERN_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #12",
        type=CivVLocationType.settler,
        game_id=12,
        database_key_prefix="settler12",
        region=regions.MODERN_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #13",
        type=CivVLocationType.settler,
        game_id=13,
        database_key_prefix="settler13",
        region=regions.MODERN_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #14",
        type=CivVLocationType.settler,
        game_id=14,
        database_key_prefix="settler14",
        region=regions.ATOMIC_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #15",
        type=CivVLocationType.settler,
        game_id=15,
        database_key_prefix="settler15",
        region=regions.ATOMIC_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #16",
        type=CivVLocationType.settler,
        game_id=16,
        database_key_prefix="settler16",
        region=regions.ATOMIC_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #17",
        type=CivVLocationType.settler,
        game_id=17,
        database_key_prefix="settler17",
        region=regions.INFORMATION_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #18",
        type=CivVLocationType.settler,
        game_id=18,
        database_key_prefix="settler18",
        region=regions.INFORMATION_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #19",
        type=CivVLocationType.settler,
        game_id=19,
        database_key_prefix="settler19",
        region=regions.INFORMATION_ERA,
        prefix="Unit",
    ),
    CivVLocationData(
        name="Settler #20",
        type=CivVLocationType.settler,
        game_id=20,
        database_key_prefix="settler20",
        region=regions.INFORMATION_ERA,
        prefix="Unit",
    ),
]
"List of all settler locations for settler sanity"
