# %% IMPORTS
from .core import CivVLocationData
from .. import regions
from ..enums import CivVLocationType

# All declaration
__all__ = [
    "TECH_LOCATIONS",
]

# %% LOCATION DECLARATIONS
TECH_LOCATIONS = [
    # All vanilla techs converted to AP techs
    CivVLocationData(
        name="Ancient AP 1",
        type=CivVLocationType.tech,
        game_id=83,
        cost=35,
        database_key_prefix="tech_ancient_ap1",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 2",
        type=CivVLocationType.tech,
        game_id=84,
        cost=35,
        database_key_prefix="tech_ancient_ap2",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 3",
        type=CivVLocationType.tech,
        game_id=85,
        cost=35,
        database_key_prefix="tech_ancient_ap3",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 4",
        type=CivVLocationType.tech,
        game_id=86,
        cost=35,
        database_key_prefix="tech_ancient_ap4",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 5",
        type=CivVLocationType.tech,
        game_id=87,
        cost=55,
        database_key_prefix="tech_ancient_ap5",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 6",
        type=CivVLocationType.tech,
        game_id=88,
        cost=55,
        database_key_prefix="tech_ancient_ap6",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 7",
        type=CivVLocationType.tech,
        game_id=89,
        cost=55,
        database_key_prefix="tech_ancient_ap7",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 8",
        type=CivVLocationType.tech,
        game_id=90,
        cost=55,
        database_key_prefix="tech_ancient_ap8",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 9",
        type=CivVLocationType.tech,
        game_id=91,
        cost=55,
        database_key_prefix="tech_ancient_ap9",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 10",
        type=CivVLocationType.tech,
        game_id=92,
        cost=55,
        database_key_prefix="tech_ancient_ap10",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Ancient AP 11",
        type=CivVLocationType.tech,
        game_id=93,
        cost=55,
        database_key_prefix="tech_ancient_ap11",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 1",
        type=CivVLocationType.tech,
        game_id=94,
        cost=85,
        database_key_prefix="tech_classical_ap1",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 2",
        type=CivVLocationType.tech,
        game_id=95,
        cost=105,
        database_key_prefix="tech_classical_ap2",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 3",
        type=CivVLocationType.tech,
        game_id=96,
        cost=105,
        database_key_prefix="tech_classical_ap3",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 4",
        type=CivVLocationType.tech,
        game_id=97,
        cost=105,
        database_key_prefix="tech_classical_ap4",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 5",
        type=CivVLocationType.tech,
        game_id=98,
        cost=175,
        database_key_prefix="tech_classical_ap5",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 6",
        type=CivVLocationType.tech,
        game_id=99,
        cost=175,
        database_key_prefix="tech_classical_ap6",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 7",
        type=CivVLocationType.tech,
        game_id=100,
        cost=175,
        database_key_prefix="tech_classical_ap7",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 8",
        type=CivVLocationType.tech,
        game_id=101,
        cost=175,
        database_key_prefix="tech_classical_ap8",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP 9",
        type=CivVLocationType.tech,
        game_id=102,
        cost=175,
        database_key_prefix="tech_classical_ap9",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 1",
        type=CivVLocationType.tech,
        game_id=103,
        cost=275,
        database_key_prefix="tech_medieval_ap1",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 2",
        type=CivVLocationType.tech,
        game_id=104,
        cost=275,
        database_key_prefix="tech_medieval_ap2",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 3",
        type=CivVLocationType.tech,
        game_id=105,
        cost=275,
        database_key_prefix="tech_medieval_ap3",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 4",
        type=CivVLocationType.tech,
        game_id=106,
        cost=275,
        database_key_prefix="tech_medieval_ap4",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 5",
        type=CivVLocationType.tech,
        game_id=107,
        cost=375,
        database_key_prefix="tech_medieval_ap5",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 6",
        type=CivVLocationType.tech,
        game_id=108,
        cost=485,
        database_key_prefix="tech_medieval_ap6",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 7",
        type=CivVLocationType.tech,
        game_id=109,
        cost=485,
        database_key_prefix="tech_medieval_ap7",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 8",
        type=CivVLocationType.tech,
        game_id=110,
        cost=485,
        database_key_prefix="tech_medieval_ap8",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 9",
        type=CivVLocationType.tech,
        game_id=111,
        cost=485,
        database_key_prefix="tech_medieval_ap9",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP 10",
        type=CivVLocationType.tech,
        game_id=112,
        cost=485,
        database_key_prefix="tech_medieval_ap10",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 1",
        type=CivVLocationType.tech,
        game_id=113,
        cost=780,
        database_key_prefix="tech_renaissance_ap1",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 2",
        type=CivVLocationType.tech,
        game_id=114,
        cost=780,
        database_key_prefix="tech_renaissance_ap2",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 3",
        type=CivVLocationType.tech,
        game_id=115,
        cost=780,
        database_key_prefix="tech_renaissance_ap3",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 4",
        type=CivVLocationType.tech,
        game_id=116,
        cost=780,
        database_key_prefix="tech_renaissance_ap4",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 5",
        type=CivVLocationType.tech,
        game_id=117,
        cost=780,
        database_key_prefix="tech_renaissance_ap5",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 6",
        type=CivVLocationType.tech,
        game_id=118,
        cost=1150,
        database_key_prefix="tech_renaissance_ap6",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 7",
        type=CivVLocationType.tech,
        game_id=119,
        cost=1150,
        database_key_prefix="tech_renaissance_ap7",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 8",
        type=CivVLocationType.tech,
        game_id=120,
        cost=1150,
        database_key_prefix="tech_renaissance_ap8",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 9",
        type=CivVLocationType.tech,
        game_id=121,
        cost=1150,
        database_key_prefix="tech_renaissance_ap9",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP 10",
        type=CivVLocationType.tech,
        game_id=122,
        cost=1150,
        database_key_prefix="tech_renaissance_ap10",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 1",
        type=CivVLocationType.tech,
        game_id=123,
        cost=1600,
        database_key_prefix="tech_industrial_ap1",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 2",
        type=CivVLocationType.tech,
        game_id=124,
        cost=1600,
        database_key_prefix="tech_industrial_ap2",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 3",
        type=CivVLocationType.tech,
        game_id=125,
        cost=1600,
        database_key_prefix="tech_industrial_ap3",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 4",
        type=CivVLocationType.tech,
        game_id=126,
        cost=1600,
        database_key_prefix="tech_industrial_ap4",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 5",
        type=CivVLocationType.tech,
        game_id=127,
        cost=1600,
        database_key_prefix="tech_industrial_ap5",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 6",
        type=CivVLocationType.tech,
        game_id=128,
        cost=1600,
        database_key_prefix="tech_industrial_ap6",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 7",
        type=CivVLocationType.tech,
        game_id=129,
        cost=2350,
        database_key_prefix="tech_industrial_ap7",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 8",
        type=CivVLocationType.tech,
        game_id=130,
        cost=2350,
        database_key_prefix="tech_industrial_ap8",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 9",
        type=CivVLocationType.tech,
        game_id=131,
        cost=2350,
        database_key_prefix="tech_industrial_ap9",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP 10",
        type=CivVLocationType.tech,
        game_id=132,
        cost=2350,
        database_key_prefix="tech_industrial_ap10",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 1",
        type=CivVLocationType.tech,
        game_id=133,
        cost=3100,
        database_key_prefix="tech_modern_ap1",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 2",
        type=CivVLocationType.tech,
        game_id=134,
        cost=3100,
        database_key_prefix="tech_modern_ap2",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 3",
        type=CivVLocationType.tech,
        game_id=135,
        cost=3100,
        database_key_prefix="tech_modern_ap3",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 4",
        type=CivVLocationType.tech,
        game_id=136,
        cost=3100,
        database_key_prefix="tech_modern_ap4",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 5",
        type=CivVLocationType.tech,
        game_id=137,
        cost=3100,
        database_key_prefix="tech_modern_ap5",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 6",
        type=CivVLocationType.tech,
        game_id=138,
        cost=4100,
        database_key_prefix="tech_modern_ap6",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 7",
        type=CivVLocationType.tech,
        game_id=139,
        cost=4100,
        database_key_prefix="tech_modern_ap7",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 8",
        type=CivVLocationType.tech,
        game_id=140,
        cost=4100,
        database_key_prefix="tech_modern_ap8",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP 9",
        type=CivVLocationType.tech,
        game_id=141,
        cost=4100,
        database_key_prefix="tech_modern_ap9",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP 1",
        type=CivVLocationType.tech,
        game_id=142,
        cost=5100,
        database_key_prefix="tech_atomic_ap1",
        region=regions.ATOMIC_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP 2",
        type=CivVLocationType.tech,
        game_id=143,
        cost=5100,
        database_key_prefix="tech_atomic_ap2",
        region=regions.ATOMIC_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP 3",
        type=CivVLocationType.tech,
        game_id=144,
        cost=5100,
        database_key_prefix="tech_atomic_ap3",
        region=regions.ATOMIC_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP 4",
        type=CivVLocationType.tech,
        game_id=145,
        cost=5100,
        database_key_prefix="tech_atomic_ap4",
        region=regions.ATOMIC_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP 5",
        type=CivVLocationType.tech,
        game_id=146,
        cost=6400,
        database_key_prefix="tech_atomic_ap5",
        region=regions.ATOMIC_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP 6",
        type=CivVLocationType.tech,
        game_id=147,
        cost=6400,
        database_key_prefix="tech_atomic_ap6",
        region=regions.ATOMIC_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP 7",
        type=CivVLocationType.tech,
        game_id=148,
        cost=6400,
        database_key_prefix="tech_atomic_ap7",
        region=regions.ATOMIC_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP 8",
        type=CivVLocationType.tech,
        game_id=149,
        cost=6400,
        database_key_prefix="tech_atomic_ap8",
        region=regions.ATOMIC_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 1",
        type=CivVLocationType.tech,
        game_id=150,
        cost=7700,
        database_key_prefix="tech_information_ap1",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 2",
        type=CivVLocationType.tech,
        game_id=151,
        cost=7700,
        database_key_prefix="tech_information_ap2",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 3",
        type=CivVLocationType.tech,
        game_id=152,
        cost=7700,
        database_key_prefix="tech_information_ap3",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 4",
        type=CivVLocationType.tech,
        game_id=153,
        cost=7700,
        database_key_prefix="tech_information_ap4",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 5",
        type=CivVLocationType.tech,
        game_id=154,
        cost=7700,
        database_key_prefix="tech_information_ap5",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 6",
        type=CivVLocationType.tech,
        game_id=155,
        cost=7700,
        database_key_prefix="tech_information_ap6",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 7",
        type=CivVLocationType.tech,
        game_id=156,
        cost=8800,
        database_key_prefix="tech_information_ap7",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 8",
        type=CivVLocationType.tech,
        game_id=157,
        cost=8800,
        database_key_prefix="tech_information_ap8",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 9",
        type=CivVLocationType.tech,
        game_id=158,
        cost=8800,
        database_key_prefix="tech_information_ap9",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 10",
        type=CivVLocationType.tech,
        game_id=159,
        cost=8800,
        database_key_prefix="tech_information_ap10",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 11",
        type=CivVLocationType.tech,
        game_id=160,
        cost=8800,
        database_key_prefix="tech_information_ap11",
        region=regions.INFORMATION_ERA_TECH,
    ),
    CivVLocationData(
        name="Information AP 12",
        type=CivVLocationType.tech,
        game_id=161,
        cost=8800,
        database_key_prefix="tech_information_ap12",
        region=regions.INFORMATION_ERA_TECH,
    ),

    # Additional techs
    CivVLocationData(
        name="Ancient AP Bonus",
        type=CivVLocationType.tech,
        game_id=162,
        cost=35,
        database_key_prefix="tech_ancient_ap_bonus",
        region=regions.ANCIENT_ERA_TECH,
    ),
    CivVLocationData(
        name="Classical AP Bonus",
        type=CivVLocationType.tech,
        game_id=163,
        cost=85,
        database_key_prefix="tech_classical_ap_bonus",
        region=regions.CLASSICAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Medieval AP Bonus",
        type=CivVLocationType.tech,
        game_id=164,
        cost=275,
        database_key_prefix="tech_medieval_ap_bonus",
        region=regions.MEDIEVAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Renaissance AP Bonus",
        type=CivVLocationType.tech,
        game_id=165,
        cost=780,
        database_key_prefix="tech_renaissance_ap_bonus",
        region=regions.RENAISSANCE_ERA_TECH,
    ),
    CivVLocationData(
        name="Industrial AP Bonus",
        type=CivVLocationType.tech,
        game_id=166,
        cost=1600,
        database_key_prefix="tech_industrial_ap_bonus",
        region=regions.INDUSTRIAL_ERA_TECH,
    ),
    CivVLocationData(
        name="Modern AP Bonus",
        type=CivVLocationType.tech,
        game_id=167,
        cost=3100,
        database_key_prefix="tech_modern_ap_bonus",
        region=regions.MODERN_ERA_TECH,
    ),
    CivVLocationData(
        name="Atomic AP Bonus",
        type=CivVLocationType.tech,
        game_id=168,
        cost=5100,
        database_key_prefix="tech_atomic_ap_bonus",
        region=regions.ATOMIC_ERA_TECH,
    ),
]
"List of all technology locations"
