# %% IMPORTS
from .core import CivVLocationData
from .. import regions
from ..enums import CivVLocationType

# All declaration
__all__ = [
    "TECH_LOCATIONS",
]


# %% LOCATION DECLARATIONS
TECH_LOCATIONS = [
    # All vanilla techs converted to AP techs
    CivVLocationData(name="Ancient AP 1", type=CivVLocationType.tech, game_id=83, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 2", type=CivVLocationType.tech, game_id=84, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 3", type=CivVLocationType.tech, game_id=85, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 4", type=CivVLocationType.tech, game_id=86, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 5", type=CivVLocationType.tech, game_id=87, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 6", type=CivVLocationType.tech, game_id=88, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 7", type=CivVLocationType.tech, game_id=89, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 8", type=CivVLocationType.tech, game_id=90, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 9", type=CivVLocationType.tech, game_id=91, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 10", type=CivVLocationType.tech, game_id=92, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Ancient AP 11", type=CivVLocationType.tech, game_id=93, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Classical AP 1", type=CivVLocationType.tech, game_id=94, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Classical AP 2", type=CivVLocationType.tech, game_id=95, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Classical AP 3", type=CivVLocationType.tech, game_id=96, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Classical AP 4", type=CivVLocationType.tech, game_id=97, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Classical AP 5", type=CivVLocationType.tech, game_id=98, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Classical AP 6", type=CivVLocationType.tech, game_id=99, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Classical AP 7", type=CivVLocationType.tech, game_id=100, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Classical AP 8", type=CivVLocationType.tech, game_id=101, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Classical AP 9", type=CivVLocationType.tech, game_id=102, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 1", type=CivVLocationType.tech, game_id=103, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 2", type=CivVLocationType.tech, game_id=104, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 3", type=CivVLocationType.tech, game_id=105, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 4", type=CivVLocationType.tech, game_id=106, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 5", type=CivVLocationType.tech, game_id=107, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 6", type=CivVLocationType.tech, game_id=108, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 7", type=CivVLocationType.tech, game_id=109, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 8", type=CivVLocationType.tech, game_id=110, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 9", type=CivVLocationType.tech, game_id=111, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Medieval AP 10", type=CivVLocationType.tech, game_id=112, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Renaissance AP 1", type=CivVLocationType.tech, game_id=113, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 2", type=CivVLocationType.tech, game_id=114, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 3", type=CivVLocationType.tech, game_id=115, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 4", type=CivVLocationType.tech, game_id=116, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 5", type=CivVLocationType.tech, game_id=117, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 6", type=CivVLocationType.tech, game_id=118, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 7", type=CivVLocationType.tech, game_id=119, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 8", type=CivVLocationType.tech, game_id=120, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 9", type=CivVLocationType.tech, game_id=121, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Renaissance AP 10", type=CivVLocationType.tech, game_id=122, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Industrial AP 1", type=CivVLocationType.tech, game_id=123, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 2", type=CivVLocationType.tech, game_id=124, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 3", type=CivVLocationType.tech, game_id=125, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 4", type=CivVLocationType.tech, game_id=126, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 5", type=CivVLocationType.tech, game_id=127, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 6", type=CivVLocationType.tech, game_id=128, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 7", type=CivVLocationType.tech, game_id=129, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 8", type=CivVLocationType.tech, game_id=130, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 9", type=CivVLocationType.tech, game_id=131, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Industrial AP 10", type=CivVLocationType.tech, game_id=132, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Modern AP 1", type=CivVLocationType.tech, game_id=133, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Modern AP 2", type=CivVLocationType.tech, game_id=134, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Modern AP 3", type=CivVLocationType.tech, game_id=135, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Modern AP 4", type=CivVLocationType.tech, game_id=136, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Modern AP 5", type=CivVLocationType.tech, game_id=137, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Modern AP 6", type=CivVLocationType.tech, game_id=138, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Modern AP 7", type=CivVLocationType.tech, game_id=139, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Modern AP 8", type=CivVLocationType.tech, game_id=140, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Modern AP 9", type=CivVLocationType.tech, game_id=141, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Atomic AP 1", type=CivVLocationType.tech, game_id=142, region=regions.ATOMIC_ERA_TECH),
    CivVLocationData(name="Atomic AP 2", type=CivVLocationType.tech, game_id=143, region=regions.ATOMIC_ERA_TECH),
    CivVLocationData(name="Atomic AP 3", type=CivVLocationType.tech, game_id=144, region=regions.ATOMIC_ERA_TECH),
    CivVLocationData(name="Atomic AP 4", type=CivVLocationType.tech, game_id=145, region=regions.ATOMIC_ERA_TECH),
    CivVLocationData(name="Atomic AP 5", type=CivVLocationType.tech, game_id=146, region=regions.ATOMIC_ERA_TECH),
    CivVLocationData(name="Atomic AP 6", type=CivVLocationType.tech, game_id=147, region=regions.ATOMIC_ERA_TECH),
    CivVLocationData(name="Atomic AP 7", type=CivVLocationType.tech, game_id=148, region=regions.ATOMIC_ERA_TECH),
    CivVLocationData(name="Atomic AP 8", type=CivVLocationType.tech, game_id=149, region=regions.ATOMIC_ERA_TECH),
    CivVLocationData(name="Information AP 1", type=CivVLocationType.tech, game_id=150, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 2", type=CivVLocationType.tech, game_id=151, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 3", type=CivVLocationType.tech, game_id=152, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 4", type=CivVLocationType.tech, game_id=153, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 5", type=CivVLocationType.tech, game_id=154, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 6", type=CivVLocationType.tech, game_id=155, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 7", type=CivVLocationType.tech, game_id=156, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 8", type=CivVLocationType.tech, game_id=157, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 9", type=CivVLocationType.tech, game_id=158, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 10", type=CivVLocationType.tech, game_id=159, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 11", type=CivVLocationType.tech, game_id=160, region=regions.INFORMATION_ERA_TECH),
    CivVLocationData(name="Information AP 12", type=CivVLocationType.tech, game_id=161, region=regions.INFORMATION_ERA_TECH),

    # Additional techs
    CivVLocationData(name="Ancient AP Bonus", type=CivVLocationType.tech, game_id=162, region=regions.ANCIENT_ERA_TECH),
    CivVLocationData(name="Classical AP Bonus", type=CivVLocationType.tech, game_id=163, region=regions.CLASSICAL_ERA_TECH),
    CivVLocationData(name="Medieval AP Bonus", type=CivVLocationType.tech, game_id=164, region=regions.MEDIEVAL_ERA_TECH),
    CivVLocationData(name="Renaissance AP Bonus", type=CivVLocationType.tech, game_id=165, region=regions.RENAISSANCE_ERA_TECH),
    CivVLocationData(name="Industrial AP Bonus", type=CivVLocationType.tech, game_id=166, region=regions.INDUSTRIAL_ERA_TECH),
    CivVLocationData(name="Modern AP Bonus", type=CivVLocationType.tech, game_id=167, region=regions.MODERN_ERA_TECH),
    CivVLocationData(name="Atomic AP Bonus", type=CivVLocationType.tech, game_id=168, region=regions.ATOMIC_ERA_TECH),
]
"List of all technology locations"
