# %% GLOBALS DEFINITIONS
# GENERAL
CONTAINER_EXTENSION: str = ".apcivv"
"Extension to use for all AP Player Containers generated by this APWorld"
GAME_NAME: str = "Civilization V"
"Name of the game this APWorld is for"
ID_OFFSET: int = 140319
"ID offset for this APWorld"

# WEBSOCKET
ADDRESS: str = "127.0.0.1"
"Localhost address"
PORT: int = 4318
"Port to use for the Firetuner"
