# %% IMPORTS
from dataclasses import dataclass, asdict
from typing import Any

# All declaration
__all__ = [
    "CivVAPModOptions",
    "CivVSlotData",
]


# %% DATACLASS DEFINITIONS
@dataclass
class CivVAPModOptions:
    satellites_meets_all: bool
    "Receiving the Satellites technology will also meet all civilizations and city-states"

    def to_dict(self) -> dict[str, Any]:
        """
        Converts this instance to a dict and returns it.

        """

        return asdict(self)


@dataclass
class CivVSlotData:
    output_file_id: str
    "Unique ID that identifies the output file generated by for this slot"
    apmod_options: CivVAPModOptions
    "Dataclass of options that need to be given to the Civ V APMod upon connection"

    def to_dict(self) -> dict[str, Any]:
        """
        Converts this instance to a dict and returns it.

        """

        return asdict(self)
