# %% IMPORTS
from dataclasses import dataclass, asdict
from typing import Any

# All declaration
__all__ = [
    "CivVSlotData",
]


# %% DATACLASS DEFINITIONS
@dataclass
class CivVSlotData:
    output_file_id: str
    "Unique ID that identifies the output file generated by for this slot"
    death_link: bool
    "Whether DeathLink is enabled"
    death_link_effect_weights: dict[str, int]
    "Weights of each death link effect"

    def to_dict(self) -> dict[str, Any]:
        """
        Converts this instance to a dict and returns it.

        """

        return asdict(self)
